/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_ARFCN_ValueGERAN_H_
#define	_ARFCN_ValueGERAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ARFCN-ValueGERAN */
typedef long	 ARFCN_ValueGERAN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ARFCN_ValueGERAN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ARFCN_ValueGERAN;
asn_struct_free_f ARFCN_ValueGERAN_free;
asn_struct_print_f ARFCN_ValueGERAN_print;
asn_constr_check_f ARFCN_ValueGERAN_constraint;
ber_type_decoder_f ARFCN_ValueGERAN_decode_ber;
der_type_encoder_f ARFCN_ValueGERAN_encode_der;
xer_type_decoder_f ARFCN_ValueGERAN_decode_xer;
xer_type_encoder_f ARFCN_ValueGERAN_encode_xer;
oer_type_decoder_f ARFCN_ValueGERAN_decode_oer;
oer_type_encoder_f ARFCN_ValueGERAN_encode_oer;
per_type_decoder_f ARFCN_ValueGERAN_decode_uper;
per_type_encoder_f ARFCN_ValueGERAN_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ARFCN_ValueGERAN_H_ */
#include <asn_internal.h>
