/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_BandParameters_r13_H_
#define	_BandParameters_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicator-r11.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandParameters_r13__supportedCSI_Proc_r13 {
	BandParameters_r13__supportedCSI_Proc_r13_n1	= 0,
	BandParameters_r13__supportedCSI_Proc_r13_n3	= 1,
	BandParameters_r13__supportedCSI_Proc_r13_n4	= 2
} e_BandParameters_r13__supportedCSI_Proc_r13;

/* Forward declarations */
struct BandParametersUL_r13;
struct BandParametersDL_r13;

/* BandParameters-r13 */
typedef struct BandParameters_r13 {
	FreqBandIndicator_r11_t	 bandEUTRA_r13;
	struct BandParametersUL_r13	*bandParametersUL_r13	/* OPTIONAL */;
	struct BandParametersDL_r13	*bandParametersDL_r13	/* OPTIONAL */;
	long	*supportedCSI_Proc_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParameters_r13_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_supportedCSI_Proc_r13_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BandParameters_r13;
extern asn_SEQUENCE_specifics_t asn_SPC_BandParameters_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_BandParameters_r13_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BandParametersUL-r13.h"
#include "BandParametersDL-r13.h"

#endif	/* _BandParameters_r13_H_ */
#include <asn_internal.h>
