/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_CellsToAddModListUTRA_TDD_H_
#define	_CellsToAddModListUTRA_TDD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellsToAddModUTRA_TDD;

/* CellsToAddModListUTRA-TDD */
typedef struct CellsToAddModListUTRA_TDD {
	A_SEQUENCE_OF(struct CellsToAddModUTRA_TDD) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellsToAddModListUTRA_TDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellsToAddModListUTRA_TDD;
extern asn_SET_OF_specifics_t asn_SPC_CellsToAddModListUTRA_TDD_specs_1;
extern asn_TYPE_member_t asn_MBR_CellsToAddModListUTRA_TDD_1[1];
extern asn_per_constraints_t asn_PER_type_CellsToAddModListUTRA_TDD_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CellsToAddModUTRA-TDD.h"

#endif	/* _CellsToAddModListUTRA_TDD_H_ */
#include <asn_internal.h>
