/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_CSI_IM_ConfigToReleaseListExt_r13_H_
#define	_CSI_IM_ConfigToReleaseListExt_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSI-IM-ConfigId-v1310.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CSI-IM-ConfigToReleaseListExt-r13 */
typedef struct CSI_IM_ConfigToReleaseListExt_r13 {
	A_SEQUENCE_OF(CSI_IM_ConfigId_v1310_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_IM_ConfigToReleaseListExt_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSI_IM_ConfigToReleaseListExt_r13;
extern asn_SET_OF_specifics_t asn_SPC_CSI_IM_ConfigToReleaseListExt_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_CSI_IM_ConfigToReleaseListExt_r13_1[1];
extern asn_per_constraints_t asn_PER_type_CSI_IM_ConfigToReleaseListExt_r13_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CSI_IM_ConfigToReleaseListExt_r13_H_ */
#include <asn_internal.h>
