/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "DL-CarrierConfigDedicated-NB-r13.h"

static int
memb_indexToMidPRB_r13_constraint_15(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -55 && value <= 54)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_downlinkBitmapNonAnchor_r13_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_downlinkBitmapNonAnchor_r13_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_dl_GapNonAnchor_r13_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_dl_GapNonAnchor_r13_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_indexToMidPRB_r13_constr_16 CC_NOTUSED = {
	{ 1, 0 }	/* (-55..54) */,
	-1};
static asn_per_constraints_t asn_PER_memb_indexToMidPRB_r13_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7, -55,  54 }	/* (-55..54) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eutra_NumCRS_Ports_r13_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eutra_NumCRS_Ports_r13_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_samePCI_Indicator_r13_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_samePCI_Indicator_r13_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eutraControlRegionSize_r13_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eutraControlRegionSize_r13_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_nrs_PowerOffsetNonAnchor_v1330_constr_26 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_nrs_PowerOffsetNonAnchor_v1330_constr_26 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_downlinkBitmapNonAnchor_r13_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, choice.useNoBitmap_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"useNoBitmap-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, choice.useAnchorBitmap_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"useAnchorBitmap-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, choice.explicitBitmapConfiguration_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DL_Bitmap_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitBitmapConfiguration-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, choice.spare),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spare"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_downlinkBitmapNonAnchor_r13_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* useNoBitmap-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* useAnchorBitmap-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* explicitBitmapConfiguration-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* spare */
};
static asn_CHOICE_specifics_t asn_SPC_downlinkBitmapNonAnchor_r13_specs_3 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, _asn_ctx),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13, present),
	sizeof(((struct DL_CarrierConfigDedicated_NB_r13__downlinkBitmapNonAnchor_r13 *)0)->present),
	asn_MAP_downlinkBitmapNonAnchor_r13_tag2el_3,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_downlinkBitmapNonAnchor_r13_3 = {
	"downlinkBitmapNonAnchor-r13",
	"downlinkBitmapNonAnchor-r13",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_downlinkBitmapNonAnchor_r13_constr_3, &asn_PER_type_downlinkBitmapNonAnchor_r13_constr_3, CHOICE_constraint },
	asn_MBR_downlinkBitmapNonAnchor_r13_3,
	4,	/* Elements count */
	&asn_SPC_downlinkBitmapNonAnchor_r13_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_dl_GapNonAnchor_r13_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, choice.useNoGap_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"useNoGap-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, choice.useAnchorGapConfig_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"useAnchorGapConfig-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, choice.explicitGapConfiguration_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_GapConfig_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitGapConfiguration-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, choice.spare),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spare"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_dl_GapNonAnchor_r13_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* useNoGap-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* useAnchorGapConfig-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* explicitGapConfiguration-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* spare */
};
static asn_CHOICE_specifics_t asn_SPC_dl_GapNonAnchor_r13_specs_8 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, _asn_ctx),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13, present),
	sizeof(((struct DL_CarrierConfigDedicated_NB_r13__dl_GapNonAnchor_r13 *)0)->present),
	asn_MAP_dl_GapNonAnchor_r13_tag2el_8,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_GapNonAnchor_r13_8 = {
	"dl-GapNonAnchor-r13",
	"dl-GapNonAnchor-r13",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_dl_GapNonAnchor_r13_constr_8, &asn_PER_type_dl_GapNonAnchor_r13_constr_8, CHOICE_constraint },
	asn_MBR_dl_GapNonAnchor_r13_8,
	4,	/* Elements count */
	&asn_SPC_dl_GapNonAnchor_r13_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_samePCI_r13_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__samePCI_r13, indexToMidPRB_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_indexToMidPRB_r13_constr_16, &asn_PER_memb_indexToMidPRB_r13_constr_16,  memb_indexToMidPRB_r13_constraint_15 },
		0, 0, /* No default value */
		"indexToMidPRB-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_samePCI_r13_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_samePCI_r13_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* indexToMidPRB-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_samePCI_r13_specs_15 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__samePCI_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__samePCI_r13, _asn_ctx),
	asn_MAP_samePCI_r13_tag2el_15,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_samePCI_r13_15 = {
	"samePCI-r13",
	"samePCI-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_samePCI_r13_tags_15,
	sizeof(asn_DEF_samePCI_r13_tags_15)
		/sizeof(asn_DEF_samePCI_r13_tags_15[0]) - 1, /* 1 */
	asn_DEF_samePCI_r13_tags_15,	/* Same as above */
	sizeof(asn_DEF_samePCI_r13_tags_15)
		/sizeof(asn_DEF_samePCI_r13_tags_15[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_samePCI_r13_15,
	1,	/* Elements count */
	&asn_SPC_samePCI_r13_specs_15	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eutra_NumCRS_Ports_r13_value2enum_18[] = {
	{ 0,	4,	"same" },
	{ 1,	4,	"four" }
};
static const unsigned int asn_MAP_eutra_NumCRS_Ports_r13_enum2value_18[] = {
	1,	/* four(1) */
	0	/* same(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_eutra_NumCRS_Ports_r13_specs_18 = {
	asn_MAP_eutra_NumCRS_Ports_r13_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_eutra_NumCRS_Ports_r13_enum2value_18,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eutra_NumCRS_Ports_r13_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eutra_NumCRS_Ports_r13_18 = {
	"eutra-NumCRS-Ports-r13",
	"eutra-NumCRS-Ports-r13",
	&asn_OP_NativeEnumerated,
	asn_DEF_eutra_NumCRS_Ports_r13_tags_18,
	sizeof(asn_DEF_eutra_NumCRS_Ports_r13_tags_18)
		/sizeof(asn_DEF_eutra_NumCRS_Ports_r13_tags_18[0]) - 1, /* 1 */
	asn_DEF_eutra_NumCRS_Ports_r13_tags_18,	/* Same as above */
	sizeof(asn_DEF_eutra_NumCRS_Ports_r13_tags_18)
		/sizeof(asn_DEF_eutra_NumCRS_Ports_r13_tags_18[0]), /* 2 */
	{ &asn_OER_type_eutra_NumCRS_Ports_r13_constr_18, &asn_PER_type_eutra_NumCRS_Ports_r13_constr_18, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eutra_NumCRS_Ports_r13_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_differentPCI_r13_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__differentPCI_r13, eutra_NumCRS_Ports_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eutra_NumCRS_Ports_r13_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-NumCRS-Ports-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_differentPCI_r13_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_differentPCI_r13_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* eutra-NumCRS-Ports-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_differentPCI_r13_specs_17 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__differentPCI_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13__differentPCI_r13, _asn_ctx),
	asn_MAP_differentPCI_r13_tag2el_17,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_differentPCI_r13_17 = {
	"differentPCI-r13",
	"differentPCI-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_differentPCI_r13_tags_17,
	sizeof(asn_DEF_differentPCI_r13_tags_17)
		/sizeof(asn_DEF_differentPCI_r13_tags_17[0]) - 1, /* 1 */
	asn_DEF_differentPCI_r13_tags_17,	/* Same as above */
	sizeof(asn_DEF_differentPCI_r13_tags_17)
		/sizeof(asn_DEF_differentPCI_r13_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_differentPCI_r13_17,
	1,	/* Elements count */
	&asn_SPC_differentPCI_r13_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_samePCI_Indicator_r13_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13, choice.samePCI_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_samePCI_r13_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"samePCI-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13, choice.differentPCI_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_differentPCI_r13_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"differentPCI-r13"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_samePCI_Indicator_r13_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* samePCI-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* differentPCI-r13 */
};
static asn_CHOICE_specifics_t asn_SPC_samePCI_Indicator_r13_specs_14 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13, _asn_ctx),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13, present),
	sizeof(((struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13__samePCI_Indicator_r13 *)0)->present),
	asn_MAP_samePCI_Indicator_r13_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_samePCI_Indicator_r13_14 = {
	"samePCI-Indicator-r13",
	"samePCI-Indicator-r13",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_samePCI_Indicator_r13_constr_14, &asn_PER_type_samePCI_Indicator_r13_constr_14, CHOICE_constraint },
	asn_MBR_samePCI_Indicator_r13_14,
	2,	/* Elements count */
	&asn_SPC_samePCI_Indicator_r13_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_eutraControlRegionSize_r13_value2enum_21[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" }
};
static const unsigned int asn_MAP_eutraControlRegionSize_r13_enum2value_21[] = {
	0,	/* n1(0) */
	1,	/* n2(1) */
	2	/* n3(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_eutraControlRegionSize_r13_specs_21 = {
	asn_MAP_eutraControlRegionSize_r13_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_eutraControlRegionSize_r13_enum2value_21,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_eutraControlRegionSize_r13_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eutraControlRegionSize_r13_21 = {
	"eutraControlRegionSize-r13",
	"eutraControlRegionSize-r13",
	&asn_OP_NativeEnumerated,
	asn_DEF_eutraControlRegionSize_r13_tags_21,
	sizeof(asn_DEF_eutraControlRegionSize_r13_tags_21)
		/sizeof(asn_DEF_eutraControlRegionSize_r13_tags_21[0]) - 1, /* 1 */
	asn_DEF_eutraControlRegionSize_r13_tags_21,	/* Same as above */
	sizeof(asn_DEF_eutraControlRegionSize_r13_tags_21)
		/sizeof(asn_DEF_eutraControlRegionSize_r13_tags_21[0]), /* 2 */
	{ &asn_OER_type_eutraControlRegionSize_r13_constr_21, &asn_PER_type_eutraControlRegionSize_r13_constr_21, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_eutraControlRegionSize_r13_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_inbandCarrierInfo_r13_13[] = {
	{ ATF_POINTER, 1, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13, samePCI_Indicator_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_samePCI_Indicator_r13_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"samePCI-Indicator-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13, eutraControlRegionSize_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_eutraControlRegionSize_r13_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutraControlRegionSize-r13"
		},
};
static const int asn_MAP_inbandCarrierInfo_r13_oms_13[] = { 0 };
static const ber_tlv_tag_t asn_DEF_inbandCarrierInfo_r13_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_inbandCarrierInfo_r13_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* samePCI-Indicator-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eutraControlRegionSize-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_inbandCarrierInfo_r13_specs_13 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13__inbandCarrierInfo_r13, _asn_ctx),
	asn_MAP_inbandCarrierInfo_r13_tag2el_13,
	2,	/* Count of tags in the map */
	asn_MAP_inbandCarrierInfo_r13_oms_13,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_inbandCarrierInfo_r13_13 = {
	"inbandCarrierInfo-r13",
	"inbandCarrierInfo-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_inbandCarrierInfo_r13_tags_13,
	sizeof(asn_DEF_inbandCarrierInfo_r13_tags_13)
		/sizeof(asn_DEF_inbandCarrierInfo_r13_tags_13[0]) - 1, /* 1 */
	asn_DEF_inbandCarrierInfo_r13_tags_13,	/* Same as above */
	sizeof(asn_DEF_inbandCarrierInfo_r13_tags_13)
		/sizeof(asn_DEF_inbandCarrierInfo_r13_tags_13[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_inbandCarrierInfo_r13_13,
	2,	/* Elements count */
	&asn_SPC_inbandCarrierInfo_r13_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_nrs_PowerOffsetNonAnchor_v1330_value2enum_26[] = {
	{ 0,	5,	"dB-12" },
	{ 1,	5,	"dB-10" },
	{ 2,	4,	"dB-8" },
	{ 3,	4,	"dB-6" },
	{ 4,	4,	"dB-4" },
	{ 5,	4,	"dB-2" },
	{ 6,	3,	"dB0" },
	{ 7,	3,	"dB3" }
};
static const unsigned int asn_MAP_nrs_PowerOffsetNonAnchor_v1330_enum2value_26[] = {
	1,	/* dB-10(1) */
	0,	/* dB-12(0) */
	5,	/* dB-2(5) */
	4,	/* dB-4(4) */
	3,	/* dB-6(3) */
	2,	/* dB-8(2) */
	6,	/* dB0(6) */
	7	/* dB3(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_nrs_PowerOffsetNonAnchor_v1330_specs_26 = {
	asn_MAP_nrs_PowerOffsetNonAnchor_v1330_value2enum_26,	/* "tag" => N; sorted by tag */
	asn_MAP_nrs_PowerOffsetNonAnchor_v1330_enum2value_26,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nrs_PowerOffsetNonAnchor_v1330_26 = {
	"nrs-PowerOffsetNonAnchor-v1330",
	"nrs-PowerOffsetNonAnchor-v1330",
	&asn_OP_NativeEnumerated,
	asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26,
	sizeof(asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26)
		/sizeof(asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26[0]) - 1, /* 1 */
	asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26,	/* Same as above */
	sizeof(asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26)
		/sizeof(asn_DEF_nrs_PowerOffsetNonAnchor_v1330_tags_26[0]), /* 2 */
	{ &asn_OER_type_nrs_PowerOffsetNonAnchor_v1330_constr_26, &asn_PER_type_nrs_PowerOffsetNonAnchor_v1330_constr_26, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_nrs_PowerOffsetNonAnchor_v1330_specs_26	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DL_CarrierConfigDedicated_NB_r13_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_CarrierConfigDedicated_NB_r13, dl_CarrierFreq_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierFreq_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-CarrierFreq-r13"
		},
	{ ATF_POINTER, 4, offsetof(struct DL_CarrierConfigDedicated_NB_r13, downlinkBitmapNonAnchor_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_downlinkBitmapNonAnchor_r13_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"downlinkBitmapNonAnchor-r13"
		},
	{ ATF_POINTER, 3, offsetof(struct DL_CarrierConfigDedicated_NB_r13, dl_GapNonAnchor_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_dl_GapNonAnchor_r13_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-GapNonAnchor-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct DL_CarrierConfigDedicated_NB_r13, inbandCarrierInfo_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_inbandCarrierInfo_r13_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"inbandCarrierInfo-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct DL_CarrierConfigDedicated_NB_r13, nrs_PowerOffsetNonAnchor_v1330),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_nrs_PowerOffsetNonAnchor_v1330_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nrs-PowerOffsetNonAnchor-v1330"
		},
};
static const int asn_MAP_DL_CarrierConfigDedicated_NB_r13_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DL_CarrierConfigDedicated_NB_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-CarrierFreq-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* downlinkBitmapNonAnchor-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dl-GapNonAnchor-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* inbandCarrierInfo-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* nrs-PowerOffsetNonAnchor-v1330 */
};
asn_SEQUENCE_specifics_t asn_SPC_DL_CarrierConfigDedicated_NB_r13_specs_1 = {
	sizeof(struct DL_CarrierConfigDedicated_NB_r13),
	offsetof(struct DL_CarrierConfigDedicated_NB_r13, _asn_ctx),
	asn_MAP_DL_CarrierConfigDedicated_NB_r13_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_DL_CarrierConfigDedicated_NB_r13_oms_1,	/* Optional members */
	3, 1,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DL_CarrierConfigDedicated_NB_r13 = {
	"DL-CarrierConfigDedicated-NB-r13",
	"DL-CarrierConfigDedicated-NB-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1,
	sizeof(asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_DL_CarrierConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DL_CarrierConfigDedicated_NB_r13_1,
	5,	/* Elements count */
	&asn_SPC_DL_CarrierConfigDedicated_NB_r13_specs_1	/* Additional specs */
};

