/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_InterFreqCarrierFreqInfo_v1360_H_
#define	_InterFreqCarrierFreqInfo_v1360_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellSelectionInfoCE1_v1360;

/* InterFreqCarrierFreqInfo-v1360 */
typedef struct InterFreqCarrierFreqInfo_v1360 {
	struct CellSelectionInfoCE1_v1360	*cellSelectionInfoCE1_v1360	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFreqCarrierFreqInfo_v1360_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqCarrierFreqInfo_v1360;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFreqCarrierFreqInfo_v1360_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFreqCarrierFreqInfo_v1360_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CellSelectionInfoCE1-v1360.h"

#endif	/* _InterFreqCarrierFreqInfo_v1360_H_ */
#include <asn_internal.h>
