/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_LoggedMeasurementConfiguration_v1080_IEs_H_
#define	_LoggedMeasurementConfiguration_v1080_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LoggedMeasurementConfiguration_v1130_IEs;

/* LoggedMeasurementConfiguration-v1080-IEs */
typedef struct LoggedMeasurementConfiguration_v1080_IEs {
	OCTET_STRING_t	*lateNonCriticalExtension_r10	/* OPTIONAL */;
	struct LoggedMeasurementConfiguration_v1130_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoggedMeasurementConfiguration_v1080_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoggedMeasurementConfiguration_v1080_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LoggedMeasurementConfiguration_v1080_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_LoggedMeasurementConfiguration_v1080_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LoggedMeasurementConfiguration-v1130-IEs.h"

#endif	/* _LoggedMeasurementConfiguration_v1080_IEs_H_ */
#include <asn_internal.h>
