/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_MBMS_InterFreqCarrierTypeList_r14_H_
#define	_MBMS_InterFreqCarrierTypeList_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBMS_CarrierType_r14;

/* MBMS-InterFreqCarrierTypeList-r14 */
typedef struct MBMS_InterFreqCarrierTypeList_r14 {
	A_SEQUENCE_OF(struct MBMS_CarrierType_r14) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_InterFreqCarrierTypeList_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_InterFreqCarrierTypeList_r14;
extern asn_SET_OF_specifics_t asn_SPC_MBMS_InterFreqCarrierTypeList_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_MBMS_InterFreqCarrierTypeList_r14_1[1];
extern asn_per_constraints_t asn_PER_type_MBMS_InterFreqCarrierTypeList_r14_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MBMS-CarrierType-r14.h"

#endif	/* _MBMS_InterFreqCarrierTypeList_r14_H_ */
#include <asn_internal.h>
