/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_MBSFN_AreaInfoList_r9_H_
#define	_MBSFN_AreaInfoList_r9_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBSFN_AreaInfo_r9;

/* MBSFN-AreaInfoList-r9 */
typedef struct MBSFN_AreaInfoList_r9 {
	A_SEQUENCE_OF(struct MBSFN_AreaInfo_r9) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSFN_AreaInfoList_r9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSFN_AreaInfoList_r9;
extern asn_SET_OF_specifics_t asn_SPC_MBSFN_AreaInfoList_r9_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSFN_AreaInfoList_r9_1[1];
extern asn_per_constraints_t asn_PER_type_MBSFN_AreaInfoList_r9_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MBSFN-AreaInfo-r9.h"

#endif	/* _MBSFN_AreaInfoList_r9_H_ */
#include <asn_internal.h>
