/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "MeasResultEUTRA.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_primaryPLMN_Suitable_r12_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_primaryPLMN_Suitable_r12_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_freqBandIndicatorPriority_r13_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_freqBandIndicatorPriority_r13_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cgi_Info_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, cellGlobalId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellGlobalId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, trackingAreaCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrackingAreaCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trackingAreaCode"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__cgi_Info, plmn_IdentityList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMN_IdentityList2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"plmn-IdentityList"
		},
};
static const int asn_MAP_cgi_Info_oms_3[] = { 2 };
static const ber_tlv_tag_t asn_DEF_cgi_Info_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_cgi_Info_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* trackingAreaCode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* plmn-IdentityList */
};
static asn_SEQUENCE_specifics_t asn_SPC_cgi_Info_specs_3 = {
	sizeof(struct MeasResultEUTRA__cgi_Info),
	offsetof(struct MeasResultEUTRA__cgi_Info, _asn_ctx),
	asn_MAP_cgi_Info_tag2el_3,
	3,	/* Count of tags in the map */
	asn_MAP_cgi_Info_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cgi_Info_3 = {
	"cgi-Info",
	"cgi-Info",
	&asn_OP_SEQUENCE,
	asn_DEF_cgi_Info_tags_3,
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]) - 1, /* 1 */
	asn_DEF_cgi_Info_tags_3,	/* Same as above */
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_cgi_Info_3,
	3,	/* Elements count */
	&asn_SPC_cgi_Info_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_primaryPLMN_Suitable_r12_value2enum_12[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_primaryPLMN_Suitable_r12_enum2value_12[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_primaryPLMN_Suitable_r12_specs_12 = {
	asn_MAP_primaryPLMN_Suitable_r12_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_primaryPLMN_Suitable_r12_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_primaryPLMN_Suitable_r12_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_primaryPLMN_Suitable_r12_12 = {
	"primaryPLMN-Suitable-r12",
	"primaryPLMN-Suitable-r12",
	&asn_OP_NativeEnumerated,
	asn_DEF_primaryPLMN_Suitable_r12_tags_12,
	sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12)
		/sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12[0]) - 1, /* 1 */
	asn_DEF_primaryPLMN_Suitable_r12_tags_12,	/* Same as above */
	sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12)
		/sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12[0]), /* 2 */
	{ &asn_OER_type_primaryPLMN_Suitable_r12_constr_12, &asn_PER_type_primaryPLMN_Suitable_r12_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_primaryPLMN_Suitable_r12_specs_12	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_freqBandIndicatorPriority_r13_value2enum_19[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_freqBandIndicatorPriority_r13_enum2value_19[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_freqBandIndicatorPriority_r13_specs_19 = {
	asn_MAP_freqBandIndicatorPriority_r13_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_freqBandIndicatorPriority_r13_enum2value_19,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_freqBandIndicatorPriority_r13_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_freqBandIndicatorPriority_r13_19 = {
	"freqBandIndicatorPriority-r13",
	"freqBandIndicatorPriority-r13",
	&asn_OP_NativeEnumerated,
	asn_DEF_freqBandIndicatorPriority_r13_tags_19,
	sizeof(asn_DEF_freqBandIndicatorPriority_r13_tags_19)
		/sizeof(asn_DEF_freqBandIndicatorPriority_r13_tags_19[0]) - 1, /* 1 */
	asn_DEF_freqBandIndicatorPriority_r13_tags_19,	/* Same as above */
	sizeof(asn_DEF_freqBandIndicatorPriority_r13_tags_19)
		/sizeof(asn_DEF_freqBandIndicatorPriority_r13_tags_19[0]), /* 2 */
	{ &asn_OER_type_freqBandIndicatorPriority_r13_constr_19, &asn_PER_type_freqBandIndicatorPriority_r13_constr_19, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_freqBandIndicatorPriority_r13_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cgi_Info_v1310_16[] = {
	{ ATF_POINTER, 3, offsetof(struct MeasResultEUTRA__measResult__cgi_Info_v1310, freqBandIndicator_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqBandIndicator_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"freqBandIndicator-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasResultEUTRA__measResult__cgi_Info_v1310, multiBandInfoList_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MultiBandInfoList_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"multiBandInfoList-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__measResult__cgi_Info_v1310, freqBandIndicatorPriority_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_freqBandIndicatorPriority_r13_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"freqBandIndicatorPriority-r13"
		},
};
static const int asn_MAP_cgi_Info_v1310_oms_16[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_cgi_Info_v1310_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_cgi_Info_v1310_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* freqBandIndicator-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* multiBandInfoList-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* freqBandIndicatorPriority-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_cgi_Info_v1310_specs_16 = {
	sizeof(struct MeasResultEUTRA__measResult__cgi_Info_v1310),
	offsetof(struct MeasResultEUTRA__measResult__cgi_Info_v1310, _asn_ctx),
	asn_MAP_cgi_Info_v1310_tag2el_16,
	3,	/* Count of tags in the map */
	asn_MAP_cgi_Info_v1310_oms_16,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cgi_Info_v1310_16 = {
	"cgi-Info-v1310",
	"cgi-Info-v1310",
	&asn_OP_SEQUENCE,
	asn_DEF_cgi_Info_v1310_tags_16,
	sizeof(asn_DEF_cgi_Info_v1310_tags_16)
		/sizeof(asn_DEF_cgi_Info_v1310_tags_16[0]) - 1, /* 1 */
	asn_DEF_cgi_Info_v1310_tags_16,	/* Same as above */
	sizeof(asn_DEF_cgi_Info_v1310_tags_16)
		/sizeof(asn_DEF_cgi_Info_v1310_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_cgi_Info_v1310_16,
	3,	/* Elements count */
	&asn_SPC_cgi_Info_v1310_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResult_7[] = {
	{ ATF_POINTER, 8, offsetof(struct MeasResultEUTRA__measResult, rsrpResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrpResult"
		},
	{ ATF_POINTER, 7, offsetof(struct MeasResultEUTRA__measResult, rsrqResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrqResult"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasResultEUTRA__measResult, additionalSI_Info_r9),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalSI_Info_r9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalSI-Info-r9"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasResultEUTRA__measResult, primaryPLMN_Suitable_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_primaryPLMN_Suitable_r12_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"primaryPLMN-Suitable-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasResultEUTRA__measResult, measResult_v1250),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResult-v1250"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasResultEUTRA__measResult, rs_sinr_Result_r13),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RS_SINR_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rs-sinr-Result-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasResultEUTRA__measResult, cgi_Info_v1310),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_cgi_Info_v1310_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cgi-Info-v1310"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__measResult, measResult_v1360),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range_v1360,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResult-v1360"
		},
};
static const int asn_MAP_measResult_oms_7[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_measResult_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResult_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rsrqResult */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* additionalSI-Info-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* primaryPLMN-Suitable-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* measResult-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* rs-sinr-Result-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cgi-Info-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* measResult-v1360 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResult_specs_7 = {
	sizeof(struct MeasResultEUTRA__measResult),
	offsetof(struct MeasResultEUTRA__measResult, _asn_ctx),
	asn_MAP_measResult_tag2el_7,
	8,	/* Count of tags in the map */
	asn_MAP_measResult_oms_7,	/* Optional members */
	2, 6,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResult_7 = {
	"measResult",
	"measResult",
	&asn_OP_SEQUENCE,
	asn_DEF_measResult_tags_7,
	sizeof(asn_DEF_measResult_tags_7)
		/sizeof(asn_DEF_measResult_tags_7[0]) - 1, /* 1 */
	asn_DEF_measResult_tags_7,	/* Same as above */
	sizeof(asn_DEF_measResult_tags_7)
		/sizeof(asn_DEF_measResult_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_measResult_7,
	8,	/* Elements count */
	&asn_SPC_measResult_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasResultEUTRA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, physCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physCellId"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA, cgi_Info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_cgi_Info_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cgi-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, measResult),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_measResult_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResult"
		},
};
static const int asn_MAP_MeasResultEUTRA_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_MeasResultEUTRA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasResultEUTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cgi-Info */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* measResult */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasResultEUTRA_specs_1 = {
	sizeof(struct MeasResultEUTRA),
	offsetof(struct MeasResultEUTRA, _asn_ctx),
	asn_MAP_MeasResultEUTRA_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasResultEUTRA_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasResultEUTRA = {
	"MeasResultEUTRA",
	"MeasResultEUTRA",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasResultEUTRA_tags_1,
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	asn_DEF_MeasResultEUTRA_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasResultEUTRA_1,
	3,	/* Elements count */
	&asn_SPC_MeasResultEUTRA_specs_1	/* Additional specs */
};

