/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_MeasResultListCBR_r14_H_
#define	_MeasResultListCBR_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultCBR_r14;

/* MeasResultListCBR-r14 */
typedef struct MeasResultListCBR_r14 {
	A_SEQUENCE_OF(struct MeasResultCBR_r14) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultListCBR_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultListCBR_r14;
extern asn_SET_OF_specifics_t asn_SPC_MeasResultListCBR_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultListCBR_r14_1[1];
extern asn_per_constraints_t asn_PER_type_MeasResultListCBR_r14_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultCBR-r14.h"

#endif	/* _MeasResultListCBR_r14_H_ */
#include <asn_internal.h>
