/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_NeighCellsToReleaseList_r12_H_
#define	_NeighCellsToReleaseList_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NeighCellsToReleaseList-r12 */
typedef struct NeighCellsToReleaseList_r12 {
	A_SEQUENCE_OF(PhysCellId_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighCellsToReleaseList_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighCellsToReleaseList_r12;
extern asn_SET_OF_specifics_t asn_SPC_NeighCellsToReleaseList_r12_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighCellsToReleaseList_r12_1[1];
extern asn_per_constraints_t asn_PER_type_NeighCellsToReleaseList_r12_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NeighCellsToReleaseList_r12_H_ */
#include <asn_internal.h>
