/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "PhysicalConfigDedicated.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_setup_constraint_71(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_antennaInfo_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_antennaInfo_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_antennaInfo_r10_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_antennaInfo_r10_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_additionalSpectrumEmissionCA_r10_constr_30 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_additionalSpectrumEmissionCA_r10_constr_30 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_setup_constr_65 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_setup_constr_65 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ce_Mode_r13_constr_63 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ce_Mode_r13_constr_63 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_setup_constr_73 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_type_setup_constr_73 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_setup_constr_73 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_memb_setup_constr_73 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_typeA_SRS_TPC_PDCCH_Group_r14_constr_71 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_typeA_SRS_TPC_PDCCH_Group_r14_constr_71 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_k_max_r14_constr_78 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_k_max_r14_constr_78 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_p_a_must_r14_constr_81 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_p_a_must_r14_constr_81 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_must_Config_r14_constr_75 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_must_Config_r14_constr_75 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ce_pdsch_pusch_EnhancementConfig_r14_constr_91 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ce_pdsch_pusch_EnhancementConfig_r14_constr_91 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2)) */};
static asn_per_constraints_t asn_PER_type_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2)) */};
static asn_per_constraints_t asn_PER_type_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2)) */};
static asn_per_constraints_t asn_PER_memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..2)) */};
static asn_per_constraints_t asn_PER_memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_antennaInfo_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__antennaInfo, choice.explicitValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__antennaInfo, choice.defaultValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultValue"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_antennaInfo_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* explicitValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* defaultValue */
};
static asn_CHOICE_specifics_t asn_SPC_antennaInfo_specs_10 = {
	sizeof(struct PhysicalConfigDedicated__antennaInfo),
	offsetof(struct PhysicalConfigDedicated__antennaInfo, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__antennaInfo, present),
	sizeof(((struct PhysicalConfigDedicated__antennaInfo *)0)->present),
	asn_MAP_antennaInfo_tag2el_10,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_antennaInfo_10 = {
	"antennaInfo",
	"antennaInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_antennaInfo_constr_10, &asn_PER_type_antennaInfo_constr_10, CHOICE_constraint },
	asn_MBR_antennaInfo_10,
	2,	/* Elements count */
	&asn_SPC_antennaInfo_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_antennaInfo_r10_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__antennaInfo_r10, choice.explicitValue_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoDedicated_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitValue-r10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__antennaInfo_r10, choice.defaultValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultValue"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_antennaInfo_r10_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* explicitValue-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* defaultValue */
};
static asn_CHOICE_specifics_t asn_SPC_antennaInfo_r10_specs_17 = {
	sizeof(struct PhysicalConfigDedicated__antennaInfo_r10),
	offsetof(struct PhysicalConfigDedicated__antennaInfo_r10, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__antennaInfo_r10, present),
	sizeof(((struct PhysicalConfigDedicated__antennaInfo_r10 *)0)->present),
	asn_MAP_antennaInfo_r10_tag2el_17,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_antennaInfo_r10_17 = {
	"antennaInfo-r10",
	"antennaInfo-r10",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_antennaInfo_r10_constr_17, &asn_PER_type_antennaInfo_r10_constr_17, CHOICE_constraint },
	asn_MBR_antennaInfo_r10_17,
	2,	/* Elements count */
	&asn_SPC_antennaInfo_r10_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_32[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10__setup, additionalSpectrumEmissionPCell_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalSpectrumEmission,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalSpectrumEmissionPCell-r10"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_32[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_32[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* additionalSpectrumEmissionPCell-r10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_32 = {
	sizeof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10__setup),
	offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10__setup, _asn_ctx),
	asn_MAP_setup_tag2el_32,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_32 = {
	"setup",
	"setup",
	&asn_OP_SEQUENCE,
	asn_DEF_setup_tags_32,
	sizeof(asn_DEF_setup_tags_32)
		/sizeof(asn_DEF_setup_tags_32[0]) - 1, /* 1 */
	asn_DEF_setup_tags_32,	/* Same as above */
	sizeof(asn_DEF_setup_tags_32)
		/sizeof(asn_DEF_setup_tags_32[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_setup_32,
	1,	/* Elements count */
	&asn_SPC_setup_specs_32	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_additionalSpectrumEmissionCA_r10_30[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_additionalSpectrumEmissionCA_r10_tag2el_30[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_additionalSpectrumEmissionCA_r10_specs_30 = {
	sizeof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10),
	offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10, present),
	sizeof(((struct PhysicalConfigDedicated__additionalSpectrumEmissionCA_r10 *)0)->present),
	asn_MAP_additionalSpectrumEmissionCA_r10_tag2el_30,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_additionalSpectrumEmissionCA_r10_30 = {
	"additionalSpectrumEmissionCA-r10",
	"additionalSpectrumEmissionCA-r10",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_additionalSpectrumEmissionCA_r10_constr_30, &asn_PER_type_additionalSpectrumEmissionCA_r10_constr_30, CHOICE_constraint },
	asn_MBR_additionalSpectrumEmissionCA_r10_30,
	2,	/* Elements count */
	&asn_SPC_additionalSpectrumEmissionCA_r10_specs_30	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_setup_value2enum_65[] = {
	{ 0,	8,	"ce-ModeA" },
	{ 1,	8,	"ce-ModeB" }
};
static const unsigned int asn_MAP_setup_enum2value_65[] = {
	0,	/* ce-ModeA(0) */
	1	/* ce-ModeB(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_setup_specs_65 = {
	asn_MAP_setup_value2enum_65,	/* "tag" => N; sorted by tag */
	asn_MAP_setup_enum2value_65,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_setup_tags_65[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_65 = {
	"setup",
	"setup",
	&asn_OP_NativeEnumerated,
	asn_DEF_setup_tags_65,
	sizeof(asn_DEF_setup_tags_65)
		/sizeof(asn_DEF_setup_tags_65[0]) - 1, /* 1 */
	asn_DEF_setup_tags_65,	/* Same as above */
	sizeof(asn_DEF_setup_tags_65)
		/sizeof(asn_DEF_setup_tags_65[0]), /* 2 */
	{ &asn_OER_type_setup_constr_65, &asn_PER_type_setup_constr_65, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_setup_specs_65	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ce_Mode_r13_63[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__ce_Mode_r13, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__ce_Mode_r13, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_setup_65,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ce_Mode_r13_tag2el_63[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_ce_Mode_r13_specs_63 = {
	sizeof(struct PhysicalConfigDedicated__ce_Mode_r13),
	offsetof(struct PhysicalConfigDedicated__ce_Mode_r13, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__ce_Mode_r13, present),
	sizeof(((struct PhysicalConfigDedicated__ce_Mode_r13 *)0)->present),
	asn_MAP_ce_Mode_r13_tag2el_63,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_Mode_r13_63 = {
	"ce-Mode-r13",
	"ce-Mode-r13",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ce_Mode_r13_constr_63, &asn_PER_type_ce_Mode_r13_constr_63, CHOICE_constraint },
	asn_MBR_ce_Mode_r13_63,
	2,	/* Elements count */
	&asn_SPC_ce_Mode_r13_specs_63	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_73[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SRS_TPC_PDCCH_Config_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_73[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_setup_specs_73 = {
	sizeof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14__setup),
	offsetof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14__setup, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_73 = {
	"setup",
	"setup",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_setup_tags_73,
	sizeof(asn_DEF_setup_tags_73)
		/sizeof(asn_DEF_setup_tags_73[0]) - 1, /* 1 */
	asn_DEF_setup_tags_73,	/* Same as above */
	sizeof(asn_DEF_setup_tags_73)
		/sizeof(asn_DEF_setup_tags_73[0]), /* 2 */
	{ &asn_OER_type_setup_constr_73, &asn_PER_type_setup_constr_73, SEQUENCE_OF_constraint },
	asn_MBR_setup_73,
	1,	/* Single element */
	&asn_SPC_setup_specs_73	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_typeA_SRS_TPC_PDCCH_Group_r14_71[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_73,
		0,
		{ &asn_OER_memb_setup_constr_73, &asn_PER_memb_setup_constr_73,  memb_setup_constraint_71 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_typeA_SRS_TPC_PDCCH_Group_r14_tag2el_71[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_typeA_SRS_TPC_PDCCH_Group_r14_specs_71 = {
	sizeof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14),
	offsetof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14, present),
	sizeof(((struct PhysicalConfigDedicated__typeA_SRS_TPC_PDCCH_Group_r14 *)0)->present),
	asn_MAP_typeA_SRS_TPC_PDCCH_Group_r14_tag2el_71,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_typeA_SRS_TPC_PDCCH_Group_r14_71 = {
	"typeA-SRS-TPC-PDCCH-Group-r14",
	"typeA-SRS-TPC-PDCCH-Group-r14",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_typeA_SRS_TPC_PDCCH_Group_r14_constr_71, &asn_PER_type_typeA_SRS_TPC_PDCCH_Group_r14_constr_71, CHOICE_constraint },
	asn_MBR_typeA_SRS_TPC_PDCCH_Group_r14_71,
	2,	/* Elements count */
	&asn_SPC_typeA_SRS_TPC_PDCCH_Group_r14_specs_71	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_k_max_r14_value2enum_78[] = {
	{ 0,	2,	"l1" },
	{ 1,	2,	"l3" }
};
static const unsigned int asn_MAP_k_max_r14_enum2value_78[] = {
	0,	/* l1(0) */
	1	/* l3(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_k_max_r14_specs_78 = {
	asn_MAP_k_max_r14_value2enum_78,	/* "tag" => N; sorted by tag */
	asn_MAP_k_max_r14_enum2value_78,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_k_max_r14_tags_78[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_k_max_r14_78 = {
	"k-max-r14",
	"k-max-r14",
	&asn_OP_NativeEnumerated,
	asn_DEF_k_max_r14_tags_78,
	sizeof(asn_DEF_k_max_r14_tags_78)
		/sizeof(asn_DEF_k_max_r14_tags_78[0]) - 1, /* 1 */
	asn_DEF_k_max_r14_tags_78,	/* Same as above */
	sizeof(asn_DEF_k_max_r14_tags_78)
		/sizeof(asn_DEF_k_max_r14_tags_78[0]), /* 2 */
	{ &asn_OER_type_k_max_r14_constr_78, &asn_PER_type_k_max_r14_constr_78, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_k_max_r14_specs_78	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_p_a_must_r14_value2enum_81[] = {
	{ 0,	4,	"dB-6" },
	{ 1,	9,	"dB-4dot77" },
	{ 2,	4,	"dB-3" },
	{ 3,	9,	"dB-1dot77" },
	{ 4,	3,	"dB0" },
	{ 5,	3,	"dB1" },
	{ 6,	3,	"dB2" },
	{ 7,	3,	"dB3" }
};
static const unsigned int asn_MAP_p_a_must_r14_enum2value_81[] = {
	3,	/* dB-1dot77(3) */
	2,	/* dB-3(2) */
	1,	/* dB-4dot77(1) */
	0,	/* dB-6(0) */
	4,	/* dB0(4) */
	5,	/* dB1(5) */
	6,	/* dB2(6) */
	7	/* dB3(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_p_a_must_r14_specs_81 = {
	asn_MAP_p_a_must_r14_value2enum_81,	/* "tag" => N; sorted by tag */
	asn_MAP_p_a_must_r14_enum2value_81,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_p_a_must_r14_tags_81[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_p_a_must_r14_81 = {
	"p-a-must-r14",
	"p-a-must-r14",
	&asn_OP_NativeEnumerated,
	asn_DEF_p_a_must_r14_tags_81,
	sizeof(asn_DEF_p_a_must_r14_tags_81)
		/sizeof(asn_DEF_p_a_must_r14_tags_81[0]) - 1, /* 1 */
	asn_DEF_p_a_must_r14_tags_81,	/* Same as above */
	sizeof(asn_DEF_p_a_must_r14_tags_81)
		/sizeof(asn_DEF_p_a_must_r14_tags_81[0]), /* 2 */
	{ &asn_OER_type_p_a_must_r14_constr_81, &asn_PER_type_p_a_must_r14_constr_81, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_p_a_must_r14_specs_81	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_77[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__must_Config_r14__setup, k_max_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_k_max_r14_78,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"k-max-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct PhysicalConfigDedicated__must_Config_r14__setup, p_a_must_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_p_a_must_r14_81,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"p-a-must-r14"
		},
};
static const int asn_MAP_setup_oms_77[] = { 1 };
static const ber_tlv_tag_t asn_DEF_setup_tags_77[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_77[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* k-max-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* p-a-must-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_77 = {
	sizeof(struct PhysicalConfigDedicated__must_Config_r14__setup),
	offsetof(struct PhysicalConfigDedicated__must_Config_r14__setup, _asn_ctx),
	asn_MAP_setup_tag2el_77,
	2,	/* Count of tags in the map */
	asn_MAP_setup_oms_77,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_77 = {
	"setup",
	"setup",
	&asn_OP_SEQUENCE,
	asn_DEF_setup_tags_77,
	sizeof(asn_DEF_setup_tags_77)
		/sizeof(asn_DEF_setup_tags_77[0]) - 1, /* 1 */
	asn_DEF_setup_tags_77,	/* Same as above */
	sizeof(asn_DEF_setup_tags_77)
		/sizeof(asn_DEF_setup_tags_77[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_setup_77,
	2,	/* Elements count */
	&asn_SPC_setup_specs_77	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_must_Config_r14_75[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__must_Config_r14, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PhysicalConfigDedicated__must_Config_r14, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_77,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_must_Config_r14_tag2el_75[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_must_Config_r14_specs_75 = {
	sizeof(struct PhysicalConfigDedicated__must_Config_r14),
	offsetof(struct PhysicalConfigDedicated__must_Config_r14, _asn_ctx),
	offsetof(struct PhysicalConfigDedicated__must_Config_r14, present),
	sizeof(((struct PhysicalConfigDedicated__must_Config_r14 *)0)->present),
	asn_MAP_must_Config_r14_tag2el_75,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_must_Config_r14_75 = {
	"must-Config-r14",
	"must-Config-r14",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_must_Config_r14_constr_75, &asn_PER_type_must_Config_r14_constr_75, CHOICE_constraint },
	asn_MBR_must_Config_r14_75,
	2,	/* Elements count */
	&asn_SPC_must_Config_r14_specs_75	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ce_pdsch_pusch_EnhancementConfig_r14_value2enum_91[] = {
	{ 0,	2,	"on" }
};
static const unsigned int asn_MAP_ce_pdsch_pusch_EnhancementConfig_r14_enum2value_91[] = {
	0	/* on(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ce_pdsch_pusch_EnhancementConfig_r14_specs_91 = {
	asn_MAP_ce_pdsch_pusch_EnhancementConfig_r14_value2enum_91,	/* "tag" => N; sorted by tag */
	asn_MAP_ce_pdsch_pusch_EnhancementConfig_r14_enum2value_91,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91[] = {
	(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_91 = {
	"ce-pdsch-pusch-EnhancementConfig-r14",
	"ce-pdsch-pusch-EnhancementConfig-r14",
	&asn_OP_NativeEnumerated,
	asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91,
	sizeof(asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91)
		/sizeof(asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91[0]) - 1, /* 1 */
	asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91,	/* Same as above */
	sizeof(asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91)
		/sizeof(asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_tags_91[0]), /* 2 */
	{ &asn_OER_type_ce_pdsch_pusch_EnhancementConfig_r14_constr_91, &asn_PER_type_ce_pdsch_pusch_EnhancementConfig_r14_constr_91, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ce_pdsch_pusch_EnhancementConfig_r14_specs_91	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_soundingRS_UL_PeriodicConfigDedicatedList_r14_97[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SoundingRS_UL_ConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97[] = {
	(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_soundingRS_UL_PeriodicConfigDedicatedList_r14_specs_97 = {
	sizeof(struct PhysicalConfigDedicated__soundingRS_UL_PeriodicConfigDedicatedList_r14),
	offsetof(struct PhysicalConfigDedicated__soundingRS_UL_PeriodicConfigDedicatedList_r14, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_97 = {
	"soundingRS-UL-PeriodicConfigDedicatedList-r14",
	"soundingRS-UL-PeriodicConfigDedicatedList-r14",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97,
	sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97)
		/sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97[0]) - 1, /* 1 */
	asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97,	/* Same as above */
	sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97)
		/sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_tags_97[0]), /* 2 */
	{ &asn_OER_type_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97, &asn_PER_type_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97, SEQUENCE_OF_constraint },
	asn_MBR_soundingRS_UL_PeriodicConfigDedicatedList_r14_97,
	1,	/* Single element */
	&asn_SPC_soundingRS_UL_PeriodicConfigDedicatedList_r14_specs_97	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_99[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SoundingRS_UL_ConfigDedicatedUpPTsExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99[] = {
	(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_specs_99 = {
	sizeof(struct PhysicalConfigDedicated__soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14),
	offsetof(struct PhysicalConfigDedicated__soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_99 = {
	"soundingRS-UL-PeriodicConfigDedicatedUpPTsExtList-r14",
	"soundingRS-UL-PeriodicConfigDedicatedUpPTsExtList-r14",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99,
	sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99)
		/sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99[0]) - 1, /* 1 */
	asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99,	/* Same as above */
	sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99)
		/sizeof(asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_tags_99[0]), /* 2 */
	{ &asn_OER_type_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99, &asn_PER_type_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99, SEQUENCE_OF_constraint },
	asn_MBR_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_99,
	1,	/* Single element */
	&asn_SPC_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_specs_99	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_soundingRS_UL_AperiodicConfigDedicatedList_r14_101[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SoundingRS_UL_ConfigDedicatedAperiodic_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101[] = {
	(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_soundingRS_UL_AperiodicConfigDedicatedList_r14_specs_101 = {
	sizeof(struct PhysicalConfigDedicated__soundingRS_UL_AperiodicConfigDedicatedList_r14),
	offsetof(struct PhysicalConfigDedicated__soundingRS_UL_AperiodicConfigDedicatedList_r14, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_101 = {
	"soundingRS-UL-AperiodicConfigDedicatedList-r14",
	"soundingRS-UL-AperiodicConfigDedicatedList-r14",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101,
	sizeof(asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101)
		/sizeof(asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101[0]) - 1, /* 1 */
	asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101,	/* Same as above */
	sizeof(asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101)
		/sizeof(asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_tags_101[0]), /* 2 */
	{ &asn_OER_type_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101, &asn_PER_type_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101, SEQUENCE_OF_constraint },
	asn_MBR_soundingRS_UL_AperiodicConfigDedicatedList_r14_101,
	1,	/* Single element */
	&asn_SPC_soundingRS_UL_AperiodicConfigDedicatedList_r14_specs_101	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_103[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SoundingRS_UL_ConfigDedicatedAperiodicUpPTsExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103[] = {
	(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_specs_103 = {
	sizeof(struct PhysicalConfigDedicated__soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14),
	offsetof(struct PhysicalConfigDedicated__soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_103 = {
	"soundingRS-UL-ConfigDedicatedApUpPTsExtList-r14",
	"soundingRS-UL-ConfigDedicatedApUpPTsExtList-r14",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103,
	sizeof(asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103)
		/sizeof(asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103[0]) - 1, /* 1 */
	asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103,	/* Same as above */
	sizeof(asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103)
		/sizeof(asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_tags_103[0]), /* 2 */
	{ &asn_OER_type_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103, &asn_PER_type_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103, SEQUENCE_OF_constraint },
	asn_MBR_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_103,
	1,	/* Single element */
	&asn_SPC_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_specs_103	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PhysicalConfigDedicated_1[] = {
	{ ATF_POINTER, 73, offsetof(struct PhysicalConfigDedicated, pdsch_ConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigDedicated"
		},
	{ ATF_POINTER, 72, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated"
		},
	{ ATF_POINTER, 71, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated"
		},
	{ ATF_POINTER, 70, offsetof(struct PhysicalConfigDedicated, uplinkPowerControlDedicated),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlDedicated"
		},
	{ ATF_POINTER, 69, offsetof(struct PhysicalConfigDedicated, tpc_PDCCH_ConfigPUCCH),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TPC_PDCCH_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tpc-PDCCH-ConfigPUCCH"
		},
	{ ATF_POINTER, 68, offsetof(struct PhysicalConfigDedicated, tpc_PDCCH_ConfigPUSCH),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TPC_PDCCH_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tpc-PDCCH-ConfigPUSCH"
		},
	{ ATF_POINTER, 67, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig"
		},
	{ ATF_POINTER, 66, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicated"
		},
	{ ATF_POINTER, 65, offsetof(struct PhysicalConfigDedicated, antennaInfo),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_antennaInfo_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfo"
		},
	{ ATF_POINTER, 64, offsetof(struct PhysicalConfigDedicated, schedulingRequestConfig),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SchedulingRequestConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedulingRequestConfig"
		},
	{ ATF_POINTER, 63, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_v920),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v920,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-v920"
		},
	{ ATF_POINTER, 62, offsetof(struct PhysicalConfigDedicated, antennaInfo_v920),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoDedicated_v920,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfo-v920"
		},
	{ ATF_POINTER, 61, offsetof(struct PhysicalConfigDedicated, antennaInfo_r10),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_antennaInfo_r10_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfo-r10"
		},
	{ ATF_POINTER, 60, offsetof(struct PhysicalConfigDedicated, antennaInfoUL_r10),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoUL_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfoUL-r10"
		},
	{ ATF_POINTER, 59, offsetof(struct PhysicalConfigDedicated, cif_Presence_r10),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cif-Presence-r10"
		},
	{ ATF_POINTER, 58, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_r10),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-r10"
		},
	{ ATF_POINTER, 57, offsetof(struct PhysicalConfigDedicated, csi_RS_Config_r10),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_Config_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-Config-r10"
		},
	{ ATF_POINTER, 56, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated_v1020),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated-v1020"
		},
	{ ATF_POINTER, 55, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated_v1020),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated-v1020"
		},
	{ ATF_POINTER, 54, offsetof(struct PhysicalConfigDedicated, schedulingRequestConfig_v1020),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SchedulingRequestConfig_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedulingRequestConfig-v1020"
		},
	{ ATF_POINTER, 53, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicated_v1020),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicated_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicated-v1020"
		},
	{ ATF_POINTER, 52, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicatedAperiodic_r10),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicatedAperiodic_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicatedAperiodic-r10"
		},
	{ ATF_POINTER, 51, offsetof(struct PhysicalConfigDedicated, uplinkPowerControlDedicated_v1020),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlDedicated_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlDedicated-v1020"
		},
	{ ATF_POINTER, 50, offsetof(struct PhysicalConfigDedicated, additionalSpectrumEmissionCA_r10),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_additionalSpectrumEmissionCA_r10_30,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalSpectrumEmissionCA-r10"
		},
	{ ATF_POINTER, 49, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigNZPToReleaseList_r11),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigNZPToReleaseList_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigNZPToReleaseList-r11"
		},
	{ ATF_POINTER, 48, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigNZPToAddModList_r11),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigNZPToAddModList_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigNZPToAddModList-r11"
		},
	{ ATF_POINTER, 47, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigZPToReleaseList_r11),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigZPToReleaseList_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigZPToReleaseList-r11"
		},
	{ ATF_POINTER, 46, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigZPToAddModList_r11),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigZPToAddModList_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigZPToAddModList-r11"
		},
	{ ATF_POINTER, 45, offsetof(struct PhysicalConfigDedicated, epdcch_Config_r11),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EPDCCH_Config_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"epdcch-Config-r11"
		},
	{ ATF_POINTER, 44, offsetof(struct PhysicalConfigDedicated, pdsch_ConfigDedicated_v1130),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigDedicated_v1130,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigDedicated-v1130"
		},
	{ ATF_POINTER, 43, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_v1130),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v1130,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-v1130"
		},
	{ ATF_POINTER, 42, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated_v1130),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated_v1130,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated-v1130"
		},
	{ ATF_POINTER, 41, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated_v1130),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated_v1130,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated-v1130"
		},
	{ ATF_POINTER, 40, offsetof(struct PhysicalConfigDedicated, uplinkPowerControlDedicated_v1130),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlDedicated_v1130,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlDedicated-v1130"
		},
	{ ATF_POINTER, 39, offsetof(struct PhysicalConfigDedicated, antennaInfo_v1250),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoDedicated_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfo-v1250"
		},
	{ ATF_POINTER, 38, offsetof(struct PhysicalConfigDedicated, eimta_MainConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EIMTA_MainConfig_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimta-MainConfig-r12"
		},
	{ ATF_POINTER, 37, offsetof(struct PhysicalConfigDedicated, eimta_MainConfigPCell_r12),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EIMTA_MainConfigServCell_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimta-MainConfigPCell-r12"
		},
	{ ATF_POINTER, 36, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated_v1250),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated-v1250"
		},
	{ ATF_POINTER, 35, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfigPCell_v1250),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfigPCell-v1250"
		},
	{ ATF_POINTER, 34, offsetof(struct PhysicalConfigDedicated, uplinkPowerControlDedicated_v1250),
		(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlDedicated_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlDedicated-v1250"
		},
	{ ATF_POINTER, 33, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated_v1250),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated-v1250"
		},
	{ ATF_POINTER, 32, offsetof(struct PhysicalConfigDedicated, csi_RS_Config_v1250),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_Config_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-Config-v1250"
		},
	{ ATF_POINTER, 31, offsetof(struct PhysicalConfigDedicated, pdsch_ConfigDedicated_v1280),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigDedicated_v1280,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigDedicated-v1280"
		},
	{ ATF_POINTER, 30, offsetof(struct PhysicalConfigDedicated, pdsch_ConfigDedicated_v1310),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigDedicated_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigDedicated-v1310"
		},
	{ ATF_POINTER, 29, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (44 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated-r13"
		},
	{ ATF_POINTER, 28, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated-r13"
		},
	{ ATF_POINTER, 27, offsetof(struct PhysicalConfigDedicated, pdcch_CandidateReductions_r13),
		(ASN_TAG_CLASS_CONTEXT | (46 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDCCH_CandidateReductions_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdcch-CandidateReductions-r13"
		},
	{ ATF_POINTER, 26, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_v1310),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-v1310"
		},
	{ ATF_POINTER, 25, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicated_v1310),
		(ASN_TAG_CLASS_CONTEXT | (48 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicated_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicated-v1310"
		},
	{ ATF_POINTER, 24, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicatedUpPTsExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (49 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicatedUpPTsExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicatedUpPTsExt-r13"
		},
	{ ATF_POINTER, 23, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicatedAperiodic_v1310),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicatedAperiodic_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicatedAperiodic-v1310"
		},
	{ ATF_POINTER, 22, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicatedAperiodicUpPTsExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigDedicatedAperiodicUpPTsExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicatedAperiodicUpPTsExt-r13"
		},
	{ ATF_POINTER, 21, offsetof(struct PhysicalConfigDedicated, csi_RS_Config_v1310),
		(ASN_TAG_CLASS_CONTEXT | (52 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_Config_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-Config-v1310"
		},
	{ ATF_POINTER, 20, offsetof(struct PhysicalConfigDedicated, ce_Mode_r13),
		(ASN_TAG_CLASS_CONTEXT | (53 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ce_Mode_r13_63,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ce-Mode-r13"
		},
	{ ATF_POINTER, 19, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigNZPToAddModListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (54 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigNZPToAddModListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigNZPToAddModListExt-r13"
		},
	{ ATF_POINTER, 18, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigNZPToReleaseListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigNZPToReleaseListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigNZPToReleaseListExt-r13"
		},
	{ ATF_POINTER, 17, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_v1320),
		(ASN_TAG_CLASS_CONTEXT | (56 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v1320,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-v1320"
		},
	{ ATF_POINTER, 16, offsetof(struct PhysicalConfigDedicated, typeA_SRS_TPC_PDCCH_Group_r14),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_typeA_SRS_TPC_PDCCH_Group_r14_71,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeA-SRS-TPC-PDCCH-Group-r14"
		},
	{ ATF_POINTER, 15, offsetof(struct PhysicalConfigDedicated, must_Config_r14),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_must_Config_r14_75,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"must-Config-r14"
		},
	{ ATF_POINTER, 14, offsetof(struct PhysicalConfigDedicated, pusch_EnhancementsConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PUSCH_EnhancementsConfig_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-EnhancementsConfig-r14"
		},
	{ ATF_POINTER, 13, offsetof(struct PhysicalConfigDedicated, ce_pdsch_pusch_EnhancementConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ce_pdsch_pusch_EnhancementConfig_r14_91,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ce-pdsch-pusch-EnhancementConfig-r14"
		},
	{ ATF_POINTER, 12, offsetof(struct PhysicalConfigDedicated, antennaInfo_v1430),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AntennaInfoDedicated_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antennaInfo-v1430"
		},
	{ ATF_POINTER, 11, offsetof(struct PhysicalConfigDedicated, pucch_ConfigDedicated_v1430),
		(ASN_TAG_CLASS_CONTEXT | (62 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigDedicated_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigDedicated-v1430"
		},
	{ ATF_POINTER, 10, offsetof(struct PhysicalConfigDedicated, pdsch_ConfigDedicated_v1430),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigDedicated_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigDedicated-v1430"
		},
	{ ATF_POINTER, 9, offsetof(struct PhysicalConfigDedicated, pusch_ConfigDedicated_v1430),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigDedicated_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigDedicated-v1430"
		},
	{ ATF_POINTER, 8, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_PeriodicConfigDedicatedList_r14),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		0,
		&asn_DEF_soundingRS_UL_PeriodicConfigDedicatedList_r14_97,
		0,
		{ &asn_OER_memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97, &asn_PER_memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constr_97,  memb_soundingRS_UL_PeriodicConfigDedicatedList_r14_constraint_1 },
		0, 0, /* No default value */
		"soundingRS-UL-PeriodicConfigDedicatedList-r14"
		},
	{ ATF_POINTER, 7, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14),
		(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
		0,
		&asn_DEF_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_99,
		0,
		{ &asn_OER_memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99, &asn_PER_memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constr_99,  memb_soundingRS_UL_PeriodicConfigDedicatedUpPTsExtList_r14_constraint_1 },
		0, 0, /* No default value */
		"soundingRS-UL-PeriodicConfigDedicatedUpPTsExtList-r14"
		},
	{ ATF_POINTER, 6, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_AperiodicConfigDedicatedList_r14),
		(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
		0,
		&asn_DEF_soundingRS_UL_AperiodicConfigDedicatedList_r14_101,
		0,
		{ &asn_OER_memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101, &asn_PER_memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constr_101,  memb_soundingRS_UL_AperiodicConfigDedicatedList_r14_constraint_1 },
		0, 0, /* No default value */
		"soundingRS-UL-AperiodicConfigDedicatedList-r14"
		},
	{ ATF_POINTER, 5, offsetof(struct PhysicalConfigDedicated, soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14),
		(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
		0,
		&asn_DEF_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_103,
		0,
		{ &asn_OER_memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103, &asn_PER_memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constr_103,  memb_soundingRS_UL_ConfigDedicatedApUpPTsExtList_r14_constraint_1 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigDedicatedApUpPTsExtList-r14"
		},
	{ ATF_POINTER, 4, offsetof(struct PhysicalConfigDedicated, csi_RS_Config_v1430),
		(ASN_TAG_CLASS_CONTEXT | (69 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_Config_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-Config-v1430"
		},
	{ ATF_POINTER, 3, offsetof(struct PhysicalConfigDedicated, csi_RS_ConfigZP_ApList_r14),
		(ASN_TAG_CLASS_CONTEXT | (70 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigZP_ApList_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csi-RS-ConfigZP-ApList-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct PhysicalConfigDedicated, cqi_ReportConfig_v1430),
		(ASN_TAG_CLASS_CONTEXT | (71 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportConfig_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cqi-ReportConfig-v1430"
		},
	{ ATF_POINTER, 1, offsetof(struct PhysicalConfigDedicated, semiOpenLoop_r14),
		(ASN_TAG_CLASS_CONTEXT | (72 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"semiOpenLoop-r14"
		},
};
static const int asn_MAP_PhysicalConfigDedicated_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72 };
static const ber_tlv_tag_t asn_DEF_PhysicalConfigDedicated_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PhysicalConfigDedicated_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pdsch-ConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pucch-ConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pusch-ConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uplinkPowerControlDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tpc-PDCCH-ConfigPUCCH */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* tpc-PDCCH-ConfigPUSCH */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cqi-ReportConfig */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* soundingRS-UL-ConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* antennaInfo */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* schedulingRequestConfig */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* cqi-ReportConfig-v920 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* antennaInfo-v920 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* antennaInfo-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* antennaInfoUL-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* cif-Presence-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* cqi-ReportConfig-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* csi-RS-Config-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* pucch-ConfigDedicated-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* pusch-ConfigDedicated-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* schedulingRequestConfig-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* soundingRS-UL-ConfigDedicated-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* soundingRS-UL-ConfigDedicatedAperiodic-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* uplinkPowerControlDedicated-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* additionalSpectrumEmissionCA-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* csi-RS-ConfigNZPToReleaseList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* csi-RS-ConfigNZPToAddModList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* csi-RS-ConfigZPToReleaseList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* csi-RS-ConfigZPToAddModList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* epdcch-Config-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* pdsch-ConfigDedicated-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* cqi-ReportConfig-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* pucch-ConfigDedicated-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* pusch-ConfigDedicated-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* uplinkPowerControlDedicated-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* antennaInfo-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* eimta-MainConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 }, /* eimta-MainConfigPCell-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 37, 0, 0 }, /* pucch-ConfigDedicated-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 38, 0, 0 }, /* cqi-ReportConfigPCell-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 39, 0, 0 }, /* uplinkPowerControlDedicated-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 40, 0, 0 }, /* pusch-ConfigDedicated-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 41, 0, 0 }, /* csi-RS-Config-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 42, 0, 0 }, /* pdsch-ConfigDedicated-v1280 */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 43, 0, 0 }, /* pdsch-ConfigDedicated-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 44, 0, 0 }, /* pucch-ConfigDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 45, 0, 0 }, /* pusch-ConfigDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 46, 0, 0 }, /* pdcch-CandidateReductions-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 47, 0, 0 }, /* cqi-ReportConfig-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (48 << 2)), 48, 0, 0 }, /* soundingRS-UL-ConfigDedicated-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 49, 0, 0 }, /* soundingRS-UL-ConfigDedicatedUpPTsExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 50, 0, 0 }, /* soundingRS-UL-ConfigDedicatedAperiodic-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 51, 0, 0 }, /* soundingRS-UL-ConfigDedicatedAperiodicUpPTsExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (52 << 2)), 52, 0, 0 }, /* csi-RS-Config-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 53, 0, 0 }, /* ce-Mode-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (54 << 2)), 54, 0, 0 }, /* csi-RS-ConfigNZPToAddModListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 55, 0, 0 }, /* csi-RS-ConfigNZPToReleaseListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (56 << 2)), 56, 0, 0 }, /* cqi-ReportConfig-v1320 */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 57, 0, 0 }, /* typeA-SRS-TPC-PDCCH-Group-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 58, 0, 0 }, /* must-Config-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 59, 0, 0 }, /* pusch-EnhancementsConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 60, 0, 0 }, /* ce-pdsch-pusch-EnhancementConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 61, 0, 0 }, /* antennaInfo-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 62, 0, 0 }, /* pucch-ConfigDedicated-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 63, 0, 0 }, /* pdsch-ConfigDedicated-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 64, 0, 0 }, /* pusch-ConfigDedicated-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 65, 0, 0 }, /* soundingRS-UL-PeriodicConfigDedicatedList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 66, 0, 0 }, /* soundingRS-UL-PeriodicConfigDedicatedUpPTsExtList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 67, 0, 0 }, /* soundingRS-UL-AperiodicConfigDedicatedList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 68, 0, 0 }, /* soundingRS-UL-ConfigDedicatedApUpPTsExtList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 69, 0, 0 }, /* csi-RS-Config-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (70 << 2)), 70, 0, 0 }, /* csi-RS-ConfigZP-ApList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (71 << 2)), 71, 0, 0 }, /* cqi-ReportConfig-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (72 << 2)), 72, 0, 0 } /* semiOpenLoop-r14 */
};
asn_SEQUENCE_specifics_t asn_SPC_PhysicalConfigDedicated_specs_1 = {
	sizeof(struct PhysicalConfigDedicated),
	offsetof(struct PhysicalConfigDedicated, _asn_ctx),
	asn_MAP_PhysicalConfigDedicated_tag2el_1,
	73,	/* Count of tags in the map */
	asn_MAP_PhysicalConfigDedicated_oms_1,	/* Optional members */
	10, 63,	/* Root/Additions */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PhysicalConfigDedicated = {
	"PhysicalConfigDedicated",
	"PhysicalConfigDedicated",
	&asn_OP_SEQUENCE,
	asn_DEF_PhysicalConfigDedicated_tags_1,
	sizeof(asn_DEF_PhysicalConfigDedicated_tags_1)
		/sizeof(asn_DEF_PhysicalConfigDedicated_tags_1[0]), /* 1 */
	asn_DEF_PhysicalConfigDedicated_tags_1,	/* Same as above */
	sizeof(asn_DEF_PhysicalConfigDedicated_tags_1)
		/sizeof(asn_DEF_PhysicalConfigDedicated_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PhysicalConfigDedicated_1,
	73,	/* Elements count */
	&asn_SPC_PhysicalConfigDedicated_specs_1	/* Additional specs */
};

