/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_PhysCellIdUTRA_FDD_H_
#define	_PhysCellIdUTRA_FDD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhysCellIdUTRA-FDD */
typedef long	 PhysCellIdUTRA_FDD_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PhysCellIdUTRA_FDD_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PhysCellIdUTRA_FDD;
asn_struct_free_f PhysCellIdUTRA_FDD_free;
asn_struct_print_f PhysCellIdUTRA_FDD_print;
asn_constr_check_f PhysCellIdUTRA_FDD_constraint;
ber_type_decoder_f PhysCellIdUTRA_FDD_decode_ber;
der_type_encoder_f PhysCellIdUTRA_FDD_encode_der;
xer_type_decoder_f PhysCellIdUTRA_FDD_decode_xer;
xer_type_encoder_f PhysCellIdUTRA_FDD_encode_xer;
oer_type_decoder_f PhysCellIdUTRA_FDD_decode_oer;
oer_type_encoder_f PhysCellIdUTRA_FDD_encode_oer;
per_type_decoder_f PhysCellIdUTRA_FDD_decode_uper;
per_type_encoder_f PhysCellIdUTRA_FDD_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysCellIdUTRA_FDD_H_ */
#include <asn_internal.h>
