/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_PSCellToAddMod_v1440_H_
#define	_PSCellToAddMod_v1440_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RadioResourceConfigCommonPSCell_v1440;

/* PSCellToAddMod-v1440 */
typedef struct PSCellToAddMod_v1440 {
	struct RadioResourceConfigCommonPSCell_v1440	*radioResourceConfigCommonPSCell_r14	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PSCellToAddMod_v1440_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PSCellToAddMod_v1440;
extern asn_SEQUENCE_specifics_t asn_SPC_PSCellToAddMod_v1440_specs_1;
extern asn_TYPE_member_t asn_MBR_PSCellToAddMod_v1440_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RadioResourceConfigCommonPSCell-v1440.h"

#endif	/* _PSCellToAddMod_v1440_H_ */
#include <asn_internal.h>
