/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "ReportConfigInterRAT.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_maxReportCells_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_b1_Threshold_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_b1_Threshold_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_b2_Threshold2_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_b2_Threshold2_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_eventId_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_eventId_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_purpose_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_purpose_constr_27 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_triggerType_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_triggerType_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_reportAmount_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_reportAmount_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_si_RequestForHO_r9_constr_43 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_si_RequestForHO_r9_constr_43 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_reportQuantityUTRA_FDD_r10_constr_45 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_reportQuantityUTRA_FDD_r10_constr_45 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_b2_Threshold1_v1250_constr_48 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_b2_Threshold1_v1250_constr_48 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_maxReportCells_constr_31 CC_NOTUSED = {
	{ 1, 1 }	/* (1..8) */,
	-1};
static asn_per_constraints_t asn_PER_memb_maxReportCells_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (1..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_b1_Threshold_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold, choice.b1_ThresholdUTRA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1-ThresholdUTRA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold, choice.b1_ThresholdGERAN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThresholdGERAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1-ThresholdGERAN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold, choice.b1_ThresholdCDMA2000),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThresholdCDMA2000,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1-ThresholdCDMA2000"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_b1_Threshold_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* b1-ThresholdUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* b1-ThresholdGERAN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* b1-ThresholdCDMA2000 */
};
static asn_CHOICE_specifics_t asn_SPC_b1_Threshold_specs_6 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold, _asn_ctx),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold, present),
	sizeof(((struct ReportConfigInterRAT__triggerType__event__eventId__eventB1__b1_Threshold *)0)->present),
	asn_MAP_b1_Threshold_tag2el_6,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_b1_Threshold_6 = {
	"b1-Threshold",
	"b1-Threshold",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_b1_Threshold_constr_6, &asn_PER_type_b1_Threshold_constr_6, CHOICE_constraint },
	asn_MBR_b1_Threshold_6,
	3,	/* Elements count */
	&asn_SPC_b1_Threshold_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventB1_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1, b1_Threshold),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_b1_Threshold_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1-Threshold"
		},
};
static const ber_tlv_tag_t asn_DEF_eventB1_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventB1_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* b1-Threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventB1_specs_5 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB1, _asn_ctx),
	asn_MAP_eventB1_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventB1_5 = {
	"eventB1",
	"eventB1",
	&asn_OP_SEQUENCE,
	asn_DEF_eventB1_tags_5,
	sizeof(asn_DEF_eventB1_tags_5)
		/sizeof(asn_DEF_eventB1_tags_5[0]) - 1, /* 1 */
	asn_DEF_eventB1_tags_5,	/* Same as above */
	sizeof(asn_DEF_eventB1_tags_5)
		/sizeof(asn_DEF_eventB1_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventB1_5,
	1,	/* Elements count */
	&asn_SPC_eventB1_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_b2_Threshold2_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2, choice.b2_Threshold2UTRA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold2UTRA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2, choice.b2_Threshold2GERAN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThresholdGERAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold2GERAN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2, choice.b2_Threshold2CDMA2000),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThresholdCDMA2000,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold2CDMA2000"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_b2_Threshold2_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* b2-Threshold2UTRA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* b2-Threshold2GERAN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* b2-Threshold2CDMA2000 */
};
static asn_CHOICE_specifics_t asn_SPC_b2_Threshold2_specs_12 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2, _asn_ctx),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2, present),
	sizeof(((struct ReportConfigInterRAT__triggerType__event__eventId__eventB2__b2_Threshold2 *)0)->present),
	asn_MAP_b2_Threshold2_tag2el_12,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_b2_Threshold2_12 = {
	"b2-Threshold2",
	"b2-Threshold2",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_b2_Threshold2_constr_12, &asn_PER_type_b2_Threshold2_constr_12, CHOICE_constraint },
	asn_MBR_b2_Threshold2_12,
	3,	/* Elements count */
	&asn_SPC_b2_Threshold2_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventB2_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2, b2_Threshold1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2, b2_Threshold2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_b2_Threshold2_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold2"
		},
};
static const ber_tlv_tag_t asn_DEF_eventB2_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventB2_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* b2-Threshold1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* b2-Threshold2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventB2_specs_10 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventB2, _asn_ctx),
	asn_MAP_eventB2_tag2el_10,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventB2_10 = {
	"eventB2",
	"eventB2",
	&asn_OP_SEQUENCE,
	asn_DEF_eventB2_tags_10,
	sizeof(asn_DEF_eventB2_tags_10)
		/sizeof(asn_DEF_eventB2_tags_10[0]) - 1, /* 1 */
	asn_DEF_eventB2_tags_10,	/* Same as above */
	sizeof(asn_DEF_eventB2_tags_10)
		/sizeof(asn_DEF_eventB2_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventB2_10,
	2,	/* Elements count */
	&asn_SPC_eventB2_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventW1_r13_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW1_r13, w1_Threshold_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WLAN_RSSI_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"w1-Threshold-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_eventW1_r13_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventW1_r13_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* w1-Threshold-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventW1_r13_specs_17 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW1_r13),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW1_r13, _asn_ctx),
	asn_MAP_eventW1_r13_tag2el_17,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventW1_r13_17 = {
	"eventW1-r13",
	"eventW1-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_eventW1_r13_tags_17,
	sizeof(asn_DEF_eventW1_r13_tags_17)
		/sizeof(asn_DEF_eventW1_r13_tags_17[0]) - 1, /* 1 */
	asn_DEF_eventW1_r13_tags_17,	/* Same as above */
	sizeof(asn_DEF_eventW1_r13_tags_17)
		/sizeof(asn_DEF_eventW1_r13_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventW1_r13_17,
	1,	/* Elements count */
	&asn_SPC_eventW1_r13_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventW2_r13_19[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW2_r13, w2_Threshold1_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WLAN_RSSI_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"w2-Threshold1-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW2_r13, w2_Threshold2_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WLAN_RSSI_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"w2-Threshold2-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_eventW2_r13_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventW2_r13_tag2el_19[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* w2-Threshold1-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* w2-Threshold2-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventW2_r13_specs_19 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW2_r13),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW2_r13, _asn_ctx),
	asn_MAP_eventW2_r13_tag2el_19,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventW2_r13_19 = {
	"eventW2-r13",
	"eventW2-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_eventW2_r13_tags_19,
	sizeof(asn_DEF_eventW2_r13_tags_19)
		/sizeof(asn_DEF_eventW2_r13_tags_19[0]) - 1, /* 1 */
	asn_DEF_eventW2_r13_tags_19,	/* Same as above */
	sizeof(asn_DEF_eventW2_r13_tags_19)
		/sizeof(asn_DEF_eventW2_r13_tags_19[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventW2_r13_19,
	2,	/* Elements count */
	&asn_SPC_eventW2_r13_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventW3_r13_22[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW3_r13, w3_Threshold_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WLAN_RSSI_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"w3-Threshold-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_eventW3_r13_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventW3_r13_tag2el_22[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* w3-Threshold-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventW3_r13_specs_22 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW3_r13),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId__eventW3_r13, _asn_ctx),
	asn_MAP_eventW3_r13_tag2el_22,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventW3_r13_22 = {
	"eventW3-r13",
	"eventW3-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_eventW3_r13_tags_22,
	sizeof(asn_DEF_eventW3_r13_tags_22)
		/sizeof(asn_DEF_eventW3_r13_tags_22[0]) - 1, /* 1 */
	asn_DEF_eventW3_r13_tags_22,	/* Same as above */
	sizeof(asn_DEF_eventW3_r13_tags_22)
		/sizeof(asn_DEF_eventW3_r13_tags_22[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventW3_r13_22,
	1,	/* Elements count */
	&asn_SPC_eventW3_r13_specs_22	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventId_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, choice.eventB1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_eventB1_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventB1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, choice.eventB2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventB2_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventB2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, choice.eventW1_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_eventW1_r13_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventW1-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, choice.eventW2_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_eventW2_r13_19,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventW2-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, choice.eventW3_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_eventW3_r13_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventW3-r13"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventId_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventB1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventB2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eventW1-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eventW2-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* eventW3-r13 */
};
static asn_CHOICE_specifics_t asn_SPC_eventId_specs_4 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event__eventId),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, _asn_ctx),
	offsetof(struct ReportConfigInterRAT__triggerType__event__eventId, present),
	sizeof(((struct ReportConfigInterRAT__triggerType__event__eventId *)0)->present),
	asn_MAP_eventId_tag2el_4,
	5,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventId_4 = {
	"eventId",
	"eventId",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_eventId_constr_4, &asn_PER_type_eventId_constr_4, CHOICE_constraint },
	asn_MBR_eventId_4,
	5,	/* Elements count */
	&asn_SPC_eventId_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_event_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event, eventId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventId_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event, hysteresis),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hysteresis"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__event, timeToTrigger),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeToTrigger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger"
		},
};
static const ber_tlv_tag_t asn_DEF_event_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_event_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger */
};
static asn_SEQUENCE_specifics_t asn_SPC_event_specs_3 = {
	sizeof(struct ReportConfigInterRAT__triggerType__event),
	offsetof(struct ReportConfigInterRAT__triggerType__event, _asn_ctx),
	asn_MAP_event_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_event_3 = {
	"event",
	"event",
	&asn_OP_SEQUENCE,
	asn_DEF_event_tags_3,
	sizeof(asn_DEF_event_tags_3)
		/sizeof(asn_DEF_event_tags_3[0]) - 1, /* 1 */
	asn_DEF_event_tags_3,	/* Same as above */
	sizeof(asn_DEF_event_tags_3)
		/sizeof(asn_DEF_event_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_event_3,
	3,	/* Elements count */
	&asn_SPC_event_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_purpose_value2enum_27[] = {
	{ 0,	20,	"reportStrongestCells" },
	{ 1,	26,	"reportStrongestCellsForSON" },
	{ 2,	9,	"reportCGI" }
};
static const unsigned int asn_MAP_purpose_enum2value_27[] = {
	2,	/* reportCGI(2) */
	0,	/* reportStrongestCells(0) */
	1	/* reportStrongestCellsForSON(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_purpose_specs_27 = {
	asn_MAP_purpose_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_purpose_enum2value_27,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_purpose_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_purpose_27 = {
	"purpose",
	"purpose",
	&asn_OP_NativeEnumerated,
	asn_DEF_purpose_tags_27,
	sizeof(asn_DEF_purpose_tags_27)
		/sizeof(asn_DEF_purpose_tags_27[0]) - 1, /* 1 */
	asn_DEF_purpose_tags_27,	/* Same as above */
	sizeof(asn_DEF_purpose_tags_27)
		/sizeof(asn_DEF_purpose_tags_27[0]), /* 2 */
	{ &asn_OER_type_purpose_constr_27, &asn_PER_type_purpose_constr_27, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_purpose_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_periodical_26[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType__periodical, purpose),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_purpose_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"purpose"
		},
};
static const ber_tlv_tag_t asn_DEF_periodical_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_periodical_tag2el_26[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* purpose */
};
static asn_SEQUENCE_specifics_t asn_SPC_periodical_specs_26 = {
	sizeof(struct ReportConfigInterRAT__triggerType__periodical),
	offsetof(struct ReportConfigInterRAT__triggerType__periodical, _asn_ctx),
	asn_MAP_periodical_tag2el_26,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_periodical_26 = {
	"periodical",
	"periodical",
	&asn_OP_SEQUENCE,
	asn_DEF_periodical_tags_26,
	sizeof(asn_DEF_periodical_tags_26)
		/sizeof(asn_DEF_periodical_tags_26[0]) - 1, /* 1 */
	asn_DEF_periodical_tags_26,	/* Same as above */
	sizeof(asn_DEF_periodical_tags_26)
		/sizeof(asn_DEF_periodical_tags_26[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_periodical_26,
	1,	/* Elements count */
	&asn_SPC_periodical_specs_26	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_triggerType_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType, choice.event),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_event_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"event"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__triggerType, choice.periodical),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_periodical_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodical"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_triggerType_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* event */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* periodical */
};
static asn_CHOICE_specifics_t asn_SPC_triggerType_specs_2 = {
	sizeof(struct ReportConfigInterRAT__triggerType),
	offsetof(struct ReportConfigInterRAT__triggerType, _asn_ctx),
	offsetof(struct ReportConfigInterRAT__triggerType, present),
	sizeof(((struct ReportConfigInterRAT__triggerType *)0)->present),
	asn_MAP_triggerType_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_triggerType_2 = {
	"triggerType",
	"triggerType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_triggerType_constr_2, &asn_PER_type_triggerType_constr_2, CHOICE_constraint },
	asn_MBR_triggerType_2,
	2,	/* Elements count */
	&asn_SPC_triggerType_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_reportAmount_value2enum_33[] = {
	{ 0,	2,	"r1" },
	{ 1,	2,	"r2" },
	{ 2,	2,	"r4" },
	{ 3,	2,	"r8" },
	{ 4,	3,	"r16" },
	{ 5,	3,	"r32" },
	{ 6,	3,	"r64" },
	{ 7,	8,	"infinity" }
};
static const unsigned int asn_MAP_reportAmount_enum2value_33[] = {
	7,	/* infinity(7) */
	0,	/* r1(0) */
	4,	/* r16(4) */
	1,	/* r2(1) */
	5,	/* r32(5) */
	2,	/* r4(2) */
	6,	/* r64(6) */
	3	/* r8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_reportAmount_specs_33 = {
	asn_MAP_reportAmount_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_reportAmount_enum2value_33,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_reportAmount_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportAmount_33 = {
	"reportAmount",
	"reportAmount",
	&asn_OP_NativeEnumerated,
	asn_DEF_reportAmount_tags_33,
	sizeof(asn_DEF_reportAmount_tags_33)
		/sizeof(asn_DEF_reportAmount_tags_33[0]) - 1, /* 1 */
	asn_DEF_reportAmount_tags_33,	/* Same as above */
	sizeof(asn_DEF_reportAmount_tags_33)
		/sizeof(asn_DEF_reportAmount_tags_33[0]), /* 2 */
	{ &asn_OER_type_reportAmount_constr_33, &asn_PER_type_reportAmount_constr_33, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportAmount_specs_33	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_si_RequestForHO_r9_value2enum_43[] = {
	{ 0,	5,	"setup" }
};
static const unsigned int asn_MAP_si_RequestForHO_r9_enum2value_43[] = {
	0	/* setup(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_si_RequestForHO_r9_specs_43 = {
	asn_MAP_si_RequestForHO_r9_value2enum_43,	/* "tag" => N; sorted by tag */
	asn_MAP_si_RequestForHO_r9_enum2value_43,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_si_RequestForHO_r9_tags_43[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_si_RequestForHO_r9_43 = {
	"si-RequestForHO-r9",
	"si-RequestForHO-r9",
	&asn_OP_NativeEnumerated,
	asn_DEF_si_RequestForHO_r9_tags_43,
	sizeof(asn_DEF_si_RequestForHO_r9_tags_43)
		/sizeof(asn_DEF_si_RequestForHO_r9_tags_43[0]) - 1, /* 1 */
	asn_DEF_si_RequestForHO_r9_tags_43,	/* Same as above */
	sizeof(asn_DEF_si_RequestForHO_r9_tags_43)
		/sizeof(asn_DEF_si_RequestForHO_r9_tags_43[0]), /* 2 */
	{ &asn_OER_type_si_RequestForHO_r9_constr_43, &asn_PER_type_si_RequestForHO_r9_constr_43, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_si_RequestForHO_r9_specs_43	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_reportQuantityUTRA_FDD_r10_value2enum_45[] = {
	{ 0,	4,	"both" }
};
static const unsigned int asn_MAP_reportQuantityUTRA_FDD_r10_enum2value_45[] = {
	0	/* both(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_reportQuantityUTRA_FDD_r10_specs_45 = {
	asn_MAP_reportQuantityUTRA_FDD_r10_value2enum_45,	/* "tag" => N; sorted by tag */
	asn_MAP_reportQuantityUTRA_FDD_r10_enum2value_45,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_reportQuantityUTRA_FDD_r10_tags_45[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportQuantityUTRA_FDD_r10_45 = {
	"reportQuantityUTRA-FDD-r10",
	"reportQuantityUTRA-FDD-r10",
	&asn_OP_NativeEnumerated,
	asn_DEF_reportQuantityUTRA_FDD_r10_tags_45,
	sizeof(asn_DEF_reportQuantityUTRA_FDD_r10_tags_45)
		/sizeof(asn_DEF_reportQuantityUTRA_FDD_r10_tags_45[0]) - 1, /* 1 */
	asn_DEF_reportQuantityUTRA_FDD_r10_tags_45,	/* Same as above */
	sizeof(asn_DEF_reportQuantityUTRA_FDD_r10_tags_45)
		/sizeof(asn_DEF_reportQuantityUTRA_FDD_r10_tags_45[0]), /* 2 */
	{ &asn_OER_type_reportQuantityUTRA_FDD_r10_constr_45, &asn_PER_type_reportQuantityUTRA_FDD_r10_constr_45, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportQuantityUTRA_FDD_r10_specs_45	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_b2_Threshold1_v1250_48[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__b2_Threshold1_v1250, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT__b2_Threshold1_v1250, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_b2_Threshold1_v1250_tag2el_48[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_b2_Threshold1_v1250_specs_48 = {
	sizeof(struct ReportConfigInterRAT__b2_Threshold1_v1250),
	offsetof(struct ReportConfigInterRAT__b2_Threshold1_v1250, _asn_ctx),
	offsetof(struct ReportConfigInterRAT__b2_Threshold1_v1250, present),
	sizeof(((struct ReportConfigInterRAT__b2_Threshold1_v1250 *)0)->present),
	asn_MAP_b2_Threshold1_v1250_tag2el_48,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_b2_Threshold1_v1250_48 = {
	"b2-Threshold1-v1250",
	"b2-Threshold1-v1250",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_b2_Threshold1_v1250_constr_48, &asn_PER_type_b2_Threshold1_v1250_constr_48, CHOICE_constraint },
	asn_MBR_b2_Threshold1_v1250_48,
	2,	/* Elements count */
	&asn_SPC_b2_Threshold1_v1250_specs_48	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ReportConfigInterRAT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT, triggerType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_triggerType_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triggerType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT, maxReportCells),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_maxReportCells_constr_31, &asn_PER_memb_maxReportCells_constr_31,  memb_maxReportCells_constraint_1 },
		0, 0, /* No default value */
		"maxReportCells"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT, reportInterval),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportInterval,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigInterRAT, reportAmount),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportAmount_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportAmount"
		},
	{ ATF_POINTER, 6, offsetof(struct ReportConfigInterRAT, si_RequestForHO_r9),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_si_RequestForHO_r9_43,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"si-RequestForHO-r9"
		},
	{ ATF_POINTER, 5, offsetof(struct ReportConfigInterRAT, reportQuantityUTRA_FDD_r10),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportQuantityUTRA_FDD_r10_45,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportQuantityUTRA-FDD-r10"
		},
	{ ATF_POINTER, 4, offsetof(struct ReportConfigInterRAT, includeLocationInfo_r11),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"includeLocationInfo-r11"
		},
	{ ATF_POINTER, 3, offsetof(struct ReportConfigInterRAT, b2_Threshold1_v1250),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_b2_Threshold1_v1250_48,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2-Threshold1-v1250"
		},
	{ ATF_POINTER, 2, offsetof(struct ReportConfigInterRAT, reportQuantityWLAN_r13),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportQuantityWLAN_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportQuantityWLAN-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct ReportConfigInterRAT, reportAnyWLAN_r14),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportAnyWLAN-r14"
		},
};
static const int asn_MAP_ReportConfigInterRAT_oms_1[] = { 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_ReportConfigInterRAT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReportConfigInterRAT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* triggerType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxReportCells */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reportInterval */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* reportAmount */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* si-RequestForHO-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* reportQuantityUTRA-FDD-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* includeLocationInfo-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* b2-Threshold1-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* reportQuantityWLAN-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* reportAnyWLAN-r14 */
};
asn_SEQUENCE_specifics_t asn_SPC_ReportConfigInterRAT_specs_1 = {
	sizeof(struct ReportConfigInterRAT),
	offsetof(struct ReportConfigInterRAT, _asn_ctx),
	asn_MAP_ReportConfigInterRAT_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_ReportConfigInterRAT_oms_1,	/* Optional members */
	0, 6,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReportConfigInterRAT = {
	"ReportConfigInterRAT",
	"ReportConfigInterRAT",
	&asn_OP_SEQUENCE,
	asn_DEF_ReportConfigInterRAT_tags_1,
	sizeof(asn_DEF_ReportConfigInterRAT_tags_1)
		/sizeof(asn_DEF_ReportConfigInterRAT_tags_1[0]), /* 1 */
	asn_DEF_ReportConfigInterRAT_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReportConfigInterRAT_tags_1)
		/sizeof(asn_DEF_ReportConfigInterRAT_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ReportConfigInterRAT_1,
	10,	/* Elements count */
	&asn_SPC_ReportConfigInterRAT_specs_1	/* Additional specs */
};

