/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_RRCConnectionRelease_v1020_IEs_H_
#define	_RRCConnectionRelease_v1020_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RRCConnectionRelease_v1320_IEs;

/* RRCConnectionRelease-v1020-IEs */
typedef struct RRCConnectionRelease_v1020_IEs {
	long	*extendedWaitTime_r10	/* OPTIONAL */;
	struct RRCConnectionRelease_v1320_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_v1020_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_v1020_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_v1020_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRelease_v1020_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionRelease-v1320-IEs.h"

#endif	/* _RRCConnectionRelease_v1020_IEs_H_ */
#include <asn_internal.h>
