/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_RRCConnectionReestablishment_r8_IEs_H_
#define	_RRCConnectionReestablishment_r8_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioResourceConfigDedicated.h"
#include "NextHopChainingCount.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RRCConnectionReestablishment_v8a0_IEs;

/* RRCConnectionReestablishment-r8-IEs */
typedef struct RRCConnectionReestablishment_r8_IEs {
	RadioResourceConfigDedicated_t	 radioResourceConfigDedicated;
	NextHopChainingCount_t	 nextHopChainingCount;
	struct RRCConnectionReestablishment_v8a0_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReestablishment_r8_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReestablishment_r8_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReestablishment_r8_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionReestablishment_r8_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionReestablishment-v8a0-IEs.h"

#endif	/* _RRCConnectionReestablishment_r8_IEs_H_ */
#include <asn_internal.h>
