/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_SCellToAddModExt_v1370_H_
#define	_SCellToAddModExt_v1370_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RadioResourceConfigCommonSCell_v10l0;

/* SCellToAddModExt-v1370 */
typedef struct SCellToAddModExt_v1370 {
	struct RadioResourceConfigCommonSCell_v10l0	*radioResourceConfigCommonSCell_v1370	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCellToAddModExt_v1370_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCellToAddModExt_v1370;
extern asn_SEQUENCE_specifics_t asn_SPC_SCellToAddModExt_v1370_specs_1;
extern asn_TYPE_member_t asn_MBR_SCellToAddModExt_v1370_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RadioResourceConfigCommonSCell-v10l0.h"

#endif	/* _SCellToAddModExt_v1370_H_ */
#include <asn_internal.h>
