/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_SL_TxPoolIdentity_v1310_H_
#define	_SL_TxPoolIdentity_v1310_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-TxPoolIdentity-v1310 */
typedef long	 SL_TxPoolIdentity_v1310_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SL_TxPoolIdentity_v1310_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SL_TxPoolIdentity_v1310;
asn_struct_free_f SL_TxPoolIdentity_v1310_free;
asn_struct_print_f SL_TxPoolIdentity_v1310_print;
asn_constr_check_f SL_TxPoolIdentity_v1310_constraint;
ber_type_decoder_f SL_TxPoolIdentity_v1310_decode_ber;
der_type_encoder_f SL_TxPoolIdentity_v1310_encode_der;
xer_type_decoder_f SL_TxPoolIdentity_v1310_decode_xer;
xer_type_encoder_f SL_TxPoolIdentity_v1310_encode_xer;
oer_type_decoder_f SL_TxPoolIdentity_v1310_decode_oer;
oer_type_encoder_f SL_TxPoolIdentity_v1310_encode_oer;
per_type_decoder_f SL_TxPoolIdentity_v1310_decode_uper;
per_type_encoder_f SL_TxPoolIdentity_v1310_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_TxPoolIdentity_v1310_H_ */
#include <asn_internal.h>
