/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_SupportedBandCombinationReduced_r13_H_
#define	_SupportedBandCombinationReduced_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BandCombinationParameters_r13;

/* SupportedBandCombinationReduced-r13 */
typedef struct SupportedBandCombinationReduced_r13 {
	A_SEQUENCE_OF(struct BandCombinationParameters_r13) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedBandCombinationReduced_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedBandCombinationReduced_r13;
extern asn_SET_OF_specifics_t asn_SPC_SupportedBandCombinationReduced_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedBandCombinationReduced_r13_1[1];
extern asn_per_constraints_t asn_PER_type_SupportedBandCombinationReduced_r13_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BandCombinationParameters-r13.h"

#endif	/* _SupportedBandCombinationReduced_r13_H_ */
#include <asn_internal.h>
