/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_SupportedBandListUTRA_FDD_H_
#define	_SupportedBandListUTRA_FDD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SupportedBandUTRA-FDD.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SupportedBandListUTRA-FDD */
typedef struct SupportedBandListUTRA_FDD {
	A_SEQUENCE_OF(SupportedBandUTRA_FDD_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedBandListUTRA_FDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedBandListUTRA_FDD;
extern asn_SET_OF_specifics_t asn_SPC_SupportedBandListUTRA_FDD_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedBandListUTRA_FDD_1[1];
extern asn_per_constraints_t asn_PER_type_SupportedBandListUTRA_FDD_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedBandListUTRA_FDD_H_ */
#include <asn_internal.h>
