/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "SystemInformationBlockType18-r12.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_commTxResourceUC_ReqAllowed_r13_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_commTxResourceUC_ReqAllowed_r13_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_commTxAllowRelayCommon_r13_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_commTxAllowRelayCommon_r13_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_commConfig_r12_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType18_r12__commConfig_r12, commRxPool_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommRxPoolList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commRxPool-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct SystemInformationBlockType18_r12__commConfig_r12, commTxPoolNormalCommon_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommTxPoolList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxPoolNormalCommon-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType18_r12__commConfig_r12, commTxPoolExceptional_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommTxPoolList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxPoolExceptional-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType18_r12__commConfig_r12, commSyncConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_SyncConfigList_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commSyncConfig-r12"
		},
};
static const int asn_MAP_commConfig_r12_oms_2[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_commConfig_r12_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_commConfig_r12_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* commRxPool-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* commTxPoolNormalCommon-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* commTxPoolExceptional-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* commSyncConfig-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_commConfig_r12_specs_2 = {
	sizeof(struct SystemInformationBlockType18_r12__commConfig_r12),
	offsetof(struct SystemInformationBlockType18_r12__commConfig_r12, _asn_ctx),
	asn_MAP_commConfig_r12_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_commConfig_r12_oms_2,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_commConfig_r12_2 = {
	"commConfig-r12",
	"commConfig-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_commConfig_r12_tags_2,
	sizeof(asn_DEF_commConfig_r12_tags_2)
		/sizeof(asn_DEF_commConfig_r12_tags_2[0]) - 1, /* 1 */
	asn_DEF_commConfig_r12_tags_2,	/* Same as above */
	sizeof(asn_DEF_commConfig_r12_tags_2)
		/sizeof(asn_DEF_commConfig_r12_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_commConfig_r12_2,
	4,	/* Elements count */
	&asn_SPC_commConfig_r12_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_commTxResourceUC_ReqAllowed_r13_value2enum_10[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_commTxResourceUC_ReqAllowed_r13_enum2value_10[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_commTxResourceUC_ReqAllowed_r13_specs_10 = {
	asn_MAP_commTxResourceUC_ReqAllowed_r13_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_commTxResourceUC_ReqAllowed_r13_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_commTxResourceUC_ReqAllowed_r13_10 = {
	"commTxResourceUC-ReqAllowed-r13",
	"commTxResourceUC-ReqAllowed-r13",
	&asn_OP_NativeEnumerated,
	asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10,
	sizeof(asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10)
		/sizeof(asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10[0]) - 1, /* 1 */
	asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10,	/* Same as above */
	sizeof(asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10)
		/sizeof(asn_DEF_commTxResourceUC_ReqAllowed_r13_tags_10[0]), /* 2 */
	{ &asn_OER_type_commTxResourceUC_ReqAllowed_r13_constr_10, &asn_PER_type_commTxResourceUC_ReqAllowed_r13_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_commTxResourceUC_ReqAllowed_r13_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_commTxAllowRelayCommon_r13_value2enum_12[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_commTxAllowRelayCommon_r13_enum2value_12[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_commTxAllowRelayCommon_r13_specs_12 = {
	asn_MAP_commTxAllowRelayCommon_r13_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_commTxAllowRelayCommon_r13_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_commTxAllowRelayCommon_r13_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_commTxAllowRelayCommon_r13_12 = {
	"commTxAllowRelayCommon-r13",
	"commTxAllowRelayCommon-r13",
	&asn_OP_NativeEnumerated,
	asn_DEF_commTxAllowRelayCommon_r13_tags_12,
	sizeof(asn_DEF_commTxAllowRelayCommon_r13_tags_12)
		/sizeof(asn_DEF_commTxAllowRelayCommon_r13_tags_12[0]) - 1, /* 1 */
	asn_DEF_commTxAllowRelayCommon_r13_tags_12,	/* Same as above */
	sizeof(asn_DEF_commTxAllowRelayCommon_r13_tags_12)
		/sizeof(asn_DEF_commTxAllowRelayCommon_r13_tags_12[0]), /* 2 */
	{ &asn_OER_type_commTxAllowRelayCommon_r13_constr_12, &asn_PER_type_commTxAllowRelayCommon_r13_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_commTxAllowRelayCommon_r13_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SystemInformationBlockType18_r12_1[] = {
	{ ATF_POINTER, 5, offsetof(struct SystemInformationBlockType18_r12, commConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_commConfig_r12_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commConfig-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct SystemInformationBlockType18_r12, lateNonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lateNonCriticalExtension"
		},
	{ ATF_POINTER, 3, offsetof(struct SystemInformationBlockType18_r12, commTxPoolNormalCommonExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommTxPoolListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxPoolNormalCommonExt-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType18_r12, commTxResourceUC_ReqAllowed_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_commTxResourceUC_ReqAllowed_r13_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxResourceUC-ReqAllowed-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType18_r12, commTxAllowRelayCommon_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_commTxAllowRelayCommon_r13_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxAllowRelayCommon-r13"
		},
};
static const int asn_MAP_SystemInformationBlockType18_r12_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SystemInformationBlockType18_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SystemInformationBlockType18_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* commConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lateNonCriticalExtension */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* commTxPoolNormalCommonExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* commTxResourceUC-ReqAllowed-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* commTxAllowRelayCommon-r13 */
};
asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType18_r12_specs_1 = {
	sizeof(struct SystemInformationBlockType18_r12),
	offsetof(struct SystemInformationBlockType18_r12, _asn_ctx),
	asn_MAP_SystemInformationBlockType18_r12_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SystemInformationBlockType18_r12_oms_1,	/* Optional members */
	2, 3,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType18_r12 = {
	"SystemInformationBlockType18-r12",
	"SystemInformationBlockType18-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_SystemInformationBlockType18_r12_tags_1,
	sizeof(asn_DEF_SystemInformationBlockType18_r12_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType18_r12_tags_1[0]), /* 1 */
	asn_DEF_SystemInformationBlockType18_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_SystemInformationBlockType18_r12_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType18_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SystemInformationBlockType18_r12_1,
	5,	/* Elements count */
	&asn_SPC_SystemInformationBlockType18_r12_specs_1	/* Additional specs */
};

