/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-Sidelink-Preconf"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_Tx_PreconfigIndex_r14_H_
#define	_Tx_PreconfigIndex_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Tx-PreconfigIndex-r14 */
typedef long	 Tx_PreconfigIndex_r14_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Tx_PreconfigIndex_r14_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Tx_PreconfigIndex_r14;
asn_struct_free_f Tx_PreconfigIndex_r14_free;
asn_struct_print_f Tx_PreconfigIndex_r14_print;
asn_constr_check_f Tx_PreconfigIndex_r14_constraint;
ber_type_decoder_f Tx_PreconfigIndex_r14_decode_ber;
der_type_encoder_f Tx_PreconfigIndex_r14_encode_der;
xer_type_decoder_f Tx_PreconfigIndex_r14_decode_xer;
xer_type_encoder_f Tx_PreconfigIndex_r14_encode_xer;
oer_type_decoder_f Tx_PreconfigIndex_r14_decode_oer;
oer_type_encoder_f Tx_PreconfigIndex_r14_encode_oer;
per_type_decoder_f Tx_PreconfigIndex_r14_decode_uper;
per_type_encoder_f Tx_PreconfigIndex_r14_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Tx_PreconfigIndex_r14_H_ */
#include <asn_internal.h>
