/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_UEAssistanceInformation_r11_IEs_H_
#define	_UEAssistanceInformation_r11_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEAssistanceInformation_r11_IEs__powerPrefIndication_r11 {
	UEAssistanceInformation_r11_IEs__powerPrefIndication_r11_normal	= 0,
	UEAssistanceInformation_r11_IEs__powerPrefIndication_r11_lowPowerConsumption	= 1
} e_UEAssistanceInformation_r11_IEs__powerPrefIndication_r11;

/* Forward declarations */
struct UEAssistanceInformation_v1430_IEs;

/* UEAssistanceInformation-r11-IEs */
typedef struct UEAssistanceInformation_r11_IEs {
	long	*powerPrefIndication_r11	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct UEAssistanceInformation_v1430_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAssistanceInformation_r11_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_powerPrefIndication_r11_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UEAssistanceInformation_r11_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAssistanceInformation_r11_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAssistanceInformation_r11_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UEAssistanceInformation-v1430-IEs.h"

#endif	/* _UEAssistanceInformation_r11_IEs_H_ */
#include <asn_internal.h>
