/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_UECapabilityEnquiry_v1180_IEs_H_
#define	_UECapabilityEnquiry_v1180_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicator-r11.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UECapabilityEnquiry_v1310_IEs;

/* UECapabilityEnquiry-v1180-IEs */
typedef struct UECapabilityEnquiry_v1180_IEs {
	struct UECapabilityEnquiry_v1180_IEs__requestedFrequencyBands_r11 {
		A_SEQUENCE_OF(FreqBandIndicator_r11_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *requestedFrequencyBands_r11;
	struct UECapabilityEnquiry_v1310_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityEnquiry_v1180_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityEnquiry_v1180_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UECapabilityEnquiry_v1180_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UECapabilityEnquiry_v1180_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UECapabilityEnquiry-v1310-IEs.h"

#endif	/* _UECapabilityEnquiry_v1180_IEs_H_ */
#include <asn_internal.h>
