/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_UEInformationRequest_r9_IEs_H_
#define	_UEInformationRequest_r9_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UEInformationRequest_v930_IEs;

/* UEInformationRequest-r9-IEs */
typedef struct UEInformationRequest_r9_IEs {
	BOOLEAN_t	 rach_ReportReq_r9;
	BOOLEAN_t	 rlf_ReportReq_r9;
	struct UEInformationRequest_v930_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationRequest_r9_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationRequest_r9_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationRequest_r9_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationRequest_r9_IEs_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UEInformationRequest-v930-IEs.h"

#endif	/* _UEInformationRequest_r9_IEs_H_ */
#include <asn_internal.h>
