/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_UEPagingCoverageInformation_r13_IEs_H_
#define	_UEPagingCoverageInformation_r13_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEPagingCoverageInformation-r13-IEs */
typedef struct UEPagingCoverageInformation_r13_IEs {
	long	*mpdcch_NumRepetition_r13	/* OPTIONAL */;
	struct UEPagingCoverageInformation_r13_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEPagingCoverageInformation_r13_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEPagingCoverageInformation_r13_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEPagingCoverageInformation_r13_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEPagingCoverageInformation_r13_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UEPagingCoverageInformation_r13_IEs_H_ */
#include <asn_internal.h>
