/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#ifndef	_UplinkPowerControlCommon_v1310_H_
#define	_UplinkPowerControlCommon_v1310_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13 {
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF16	= 0,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF15	= 1,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF14	= 2,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF13	= 3,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF12	= 4,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF11	= 5,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_deltaF10	= 6,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13_spare1	= 7
} e_UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format4_r13;
typedef enum UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13 {
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF13	= 0,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF12	= 1,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF11	= 2,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF10	= 3,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF9	= 4,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF8	= 5,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_deltaF7	= 6,
	UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13_spare1	= 7
} e_UplinkPowerControlCommon_v1310__deltaF_PUCCH_Format5_13;

/* UplinkPowerControlCommon-v1310 */
typedef struct UplinkPowerControlCommon_v1310 {
	long	*deltaF_PUCCH_Format4_r13	/* OPTIONAL */;
	long	*deltaF_PUCCH_Format5_13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkPowerControlCommon_v1310_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_deltaF_PUCCH_Format4_r13_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_deltaF_PUCCH_Format5_13_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UplinkPowerControlCommon_v1310;
extern asn_SEQUENCE_specifics_t asn_SPC_UplinkPowerControlCommon_v1310_specs_1;
extern asn_TYPE_member_t asn_MBR_UplinkPowerControlCommon_v1310_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkPowerControlCommon_v1310_H_ */
#include <asn_internal.h>
