/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "lte-rrc-14.7.0.asn1"
 * 	`asn1c -gen-PER -fcompound-names -no-gen-example`
 */

#include "VarShortMAC-Input-NB-r13.h"

/*
 * This type is implemented using VarShortMAC_Input,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_VarShortMAC_Input_NB_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_VarShortMAC_Input_NB_r13 = {
	"VarShortMAC-Input-NB-r13",
	"VarShortMAC-Input-NB-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_VarShortMAC_Input_NB_r13_tags_1,
	sizeof(asn_DEF_VarShortMAC_Input_NB_r13_tags_1)
		/sizeof(asn_DEF_VarShortMAC_Input_NB_r13_tags_1[0]), /* 1 */
	asn_DEF_VarShortMAC_Input_NB_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_VarShortMAC_Input_NB_r13_tags_1)
		/sizeof(asn_DEF_VarShortMAC_Input_NB_r13_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VarShortMAC_Input_1,
	3,	/* Elements count */
	&asn_SPC_VarShortMAC_Input_specs_1	/* Additional specs */
};

